In [115]:
import pandas as pd


link="https://github.com/PoliticayGobiernoPUCP/Gob_TomaDeDecisiones/raw/refs/heads/master/dataCrim.xlsx"
crim=pd.read_excel(link,dtype={'cod': str})
crim.head()

,dep,prov,cod,distrito,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,AMAZONAS,BAGUA,010201,BAGUA,247,193,50,19,109,61,71,91,64,75
1,AMAZONAS,NaN,010202,ARAMANGO,16,36,50,65,70,35,51,65,48,29
2,AMAZONAS,NaN,010203,COPALLIN,1,23,54,60,51,47,27,17,23,34
3,AMAZONAS,NaN,010204,EL PARCO,2,1,NaN,4,5,5,10,4,33,8
4,AMAZONAS,NaN,010205,IMAZA,58,72,58,92,115,100,138,101,74,82

In [118]:
crim['prov']=crim.prov.ffill()

In [119]:
crim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1858 entries, 0 to 1857
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   dep       1858 non-null   object
 1   prov      1858 non-null   object
 2   cod       1858 non-null   object
 3   distrito  1858 non-null   object
 4   2015      1509 non-null   object
 5   2016      1516 non-null   object
 6   2017      1633 non-null   object
 7   2018      1600 non-null   object
 8   2019      1505 non-null   object
 9   2020      1590 non-null   object
 10  2021      1667 non-null   object
 11  2022      1668 non-null   object
 12  2023      1671 non-null   object
 13  2024      1617 non-null   object
dtypes: object(14)
memory usage: 203.3+ KB

In [120]:
crim.replace({'dep':{'LIMA METROPOLITANA':'LIMA'}},inplace=True)

In [121]:
import geopandas as gpd

dis=gpd.read_file('DISTRITOS1874.shp')
dis.head()

,DEPARTAMEN,PROVINCIA,DISTRITO,INSTITUCIO,geometry
0,TACNA,TACNA,CORONEL GREGORIO ALBARRACIN LANCHIPA,IGN,"POLYGON ((-70.17413 -18.12896, -70.17461 -18.1..."
1,TACNA,TACNA,POCOLLAY,IGN,"POLYGON ((-69.93475 -17.92557, -69.90467 -17.9..."
2,TACNA,TACNA,CALANA,IGN,"POLYGON ((-70.11604 -17.91106, -70.11457 -17.9..."
3,TACNA,TACNA,TACNA,IGN,"POLYGON ((-70.31490 -17.94498, -70.30682 -17.9..."
4,TACNA,TACNA,SAMA,IGN,"POLYGON ((-70.42497 -17.88934, -70.48022 -17.9..."

In [122]:
from unidecode import unidecode

dis['DISTRITO']=dis.DISTRITO.apply(unidecode)
crim['distrito']= crim.distrito.apply(unidecode)

In [123]:
colsCrim=['dep','prov','distrito']
colsDis=['DEPARTAMEN','PROVINCIA','DISTRITO']
concatRowVals=lambda row: '_'.join(row.values.astype(str))
crim['merger']=crim[colsCrim].apply(concatRowVals, axis=1)
dis['merger']=dis[colsDis].apply(concatRowVals, axis=1)

In [124]:
onlyCrim=set(crim.merger) - set(dis.merger)
onlyCrim

{'APURIMAC_AYMARAES_CARAYBAMBA',
 'APURIMAC_CHINCHEROS_ANCO_HUALLO',
 'AREQUIPA_CAMANA_CAMANA',
 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCARCEL',
 'AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS',
 'AYACUCHO_VILCAS HUAMAN_ACCOMARCA',
 'AYACUCHO_VILCAS HUAMAN_CARHUANCA',
 'AYACUCHO_VILCAS HUAMAN_CONCEPCION',
 'AYACUCHO_VILCAS HUAMAN_HUAMBALPA',
 'AYACUCHO_VILCAS HUAMAN_INDEPENDENCIA',
 'AYACUCHO_VILCAS HUAMAN_SAURAMA',
 'AYACUCHO_VILCAS HUAMAN_VILCAS HUAMAN',
 'AYACUCHO_VILCAS HUAMAN_VISCHONGO',
 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO',
 'CAJAMARCA_JAEN_PUCARA',
 'CUSCO_ACOMAYO_SANGARARA',
 'HUANCAVELICA_ANGARAES_HUANCA-HUANCA',
 'HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE',
 'HUANCAVELICA_CASTROVIRREYNA_TANTARA',
 'HUANUCO_HUANUCO_QUISQUI (KICHKI)',
 'HUANUCO_MARAяN_CHOLON',
 'HUANUCO_MARAяN_HUACRACHUCO',
 'HUANUCO_MARAяN_LA MORADA',
 'HUANUCO_MARAяN_SAN BUENAVENTURA',
 'HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA',
 'ICA_ICA_SAN JOSE DE LOS MOLINOS',
 'ICA_NASCA_CHANGUILLO',
 'ICA_NASCA_EL INGENIO',
 'ICA_NASCA_MARCONA',
 'ICA_NASCA_NASCA',
 'ICA_NASCA_VISTA ALEGRE',
 'JUNIN_CHUPACA_SAN JUAN DE ISCOS',
 'JUNIN_HUANCAYO_PUCARA',
 'JUNIN_JAUJA_MASMA CHICCHE',
 'JUNIN_JAUJA_TUNAN MARCA',
 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYAN',
 'LA LIBERTAD_GRAN CHIMU_CASCAS',
 'LA LIBERTAD_GRAN CHIMU_LUCMA',
 'LA LIBERTAD_GRAN CHIMU_MARMOT',
 'LA LIBERTAD_GRAN CHIMU_SAYAPULLO',
 'LA LIBERTAD_VIRU_CHAO',
 'LA LIBERTAD_VIRU_GUADALUPITO',
 'LA LIBERTAD_VIRU_VIRU',
 'LAMBAYEQUE_FERREсFE_CANARIS',
 'LAMBAYEQUE_FERREсFE_FERRENAFE',
 'LAMBAYEQUE_FERREсFE_INCAHUASI',
 'LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO',
 'LAMBAYEQUE_FERREсFE_PITIPO',
 'LAMBAYEQUE_FERREсFE_PUEBLO NUEVO',
 'LIMA_CAхTE_ASIA',
 'LIMA_CAхTE_CALANGO',
 'LIMA_CAхTE_CERRO AZUL',
 'LIMA_CAхTE_CHILCA',
 'LIMA_CAхTE_COAYLLO',
 'LIMA_CAхTE_IMPERIAL',
 'LIMA_CAхTE_LUNAHUANA',
 'LIMA_CAхTE_MALA',
 'LIMA_CAхTE_NUEVO IMPERIAL',
 'LIMA_CAхTE_PACARAN',
 'LIMA_CAхTE_QUILMANA',
 'LIMA_CAхTE_SAN ANTONIO',
 'LIMA_CAхTE_SAN LUIS',
 'LIMA_CAхTE_SAN VICENTE DE CANETE',
 'LIMA_CAхTE_SANTA CRUZ DE FLORES',
 'LIMA_CAхTE_ZUNIGA',
 'LIMA_LIMA_PUEBLO LIBRE',
 'LIMA_YAUYOS_ALLAUCA',
 'LORETO_DATEM DEL MARAяN_ANDOAS',
 'LORETO_DATEM DEL MARAяN_BARRANCA',
 'LORETO_DATEM DEL MARAяN_CAHUAPANAS',
 'LORETO_DATEM DEL MARAяN_MANSERICHE',
 'LORETO_DATEM DEL MARAяN_MORONA',
 'LORETO_DATEM DEL MARAяN_PASTAZA',
 'PIURA_SECHURA_RINCONADA LLICUAR',
 'PUNO_LAMPA_PUCARA',
 'SAN MARTIN_PICOTA_TRES UNIDOS',
 'SAN MARTIN_RIOJA_ELIAS SOPLIN VARGAS',
 'SAN MARTIN_SAN MARTIN_PAPAPLAYA',
 'TACNA_TARATA_ESTIQUE-PAMPA',
 'UCAYALI_PURUS_PURUS'}

In [125]:
onlyDis=set(dis.merger)-set(crim.merger)
onlyDis

{'ANCASH_AIJA_HUACLLAN',
 'ANCASH_BOLOGNESI_CANIS',
 'APURIMAC_AYMARAES_CARAIBAMBA',
 'APURIMAC_CHINCHEROS_ANCO HUALLO',
 'APURIMAC_CHINCHEROS_EL PORVENIR',
 'APURIMAC_CHINCHEROS_LOS CHANKAS',
 'AREQUIPA_CAMANA_CAMANA ',
 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCaRCEL',
 'AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS',
 'AYACUCHO_LA MAR_ORONCCOY',
 'AYACUCHO_VILCAS-HUAMAN_ACCOMARCA',
 'AYACUCHO_VILCAS-HUAMAN_CARHUANCA',
 'AYACUCHO_VILCAS-HUAMAN_CONCEPCION',
 'AYACUCHO_VILCAS-HUAMAN_HUAMBALPA',
 'AYACUCHO_VILCAS-HUAMAN_INDEPENDENCIA',
 'AYACUCHO_VILCAS-HUAMAN_SAURAMA',
 'AYACUCHO_VILCAS-HUAMAN_VILCAS HUAMAN',
 'AYACUCHO_VILCAS-HUAMAN_VISCHONGO',
 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED',
 'CAJAMARCA_JAEN_PUCARA ',
 'CUSCO_ACOMAYO_SANGARARA ',
 'HUANCAVELICA_ANGARAES_HUALLAY GRANDE',
 'HUANCAVELICA_ANGARAES_HUANCA HUANCA',
 'HUANCAVELICA_CASTROVIRREYNA_TANTARA ',
 'HUANCAVELICA_HUAYTARA_SAN ISIDRO',
 'HUANCAVELICA_TAYACAJA_SANTIAGO DE TUCUMA',
 'HUANUCO_HUANUCO_QUISQUI',
 'HUANUCO_MARAÑON_CHOLON',
 'HUANUCO_MARAÑON_HUACRACHUCO',
 'HUANUCO_MARAÑON_LA MORADA',
 'HUANUCO_MARAÑON_SAN BUENAVENTURA',
 'HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA',
 'ICA_ICA_SAN JOSE DE  LOS MOLINOS',
 'ICA_NAZCA_CHANGUILLO',
 'ICA_NAZCA_EL INGENIO',
 'ICA_NAZCA_MARCONA',
 'ICA_NAZCA_NAZCA',
 'ICA_NAZCA_VISTA ALEGRE',
 'JUNIN_CHUPACA_SAN JUAN DE YSCOS',
 'JUNIN_HUANCAYO_PUCARA ',
 'JUNIN_JAUJA_MASMA-CHICCHE',
 'JUNIN_JAUJA_TUNAN-MARCA',
 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYaN',
 'LA LIBERTAD_GRAN CHIMÚ_CASCAS',
 'LA LIBERTAD_GRAN CHIMÚ_LUCMA',
 'LA LIBERTAD_GRAN CHIMÚ_MARMOT',
 'LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO',
 'LA LIBERTAD_VIRÚ_CHAO',
 'LA LIBERTAD_VIRÚ_GUADALUPITO',
 'LA LIBERTAD_VIRÚ_VIRU',
 'LAMBAYEQUE_FERREÑAFE_CANARIS',
 'LAMBAYEQUE_FERREÑAFE_FERRENAFE',
 'LAMBAYEQUE_FERREÑAFE_INCAHUASI',
 'LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO',
 'LAMBAYEQUE_FERREÑAFE_PITIPO',
 'LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO',
 'LIMA_CAJATAMBO_COPA',
 'LIMA_CAÑETE_ASIA',
 'LIMA_CAÑETE_CALANGO',
 'LIMA_CAÑETE_CERRO AZUL',
 'LIMA_CAÑETE_CHILCA',
 'LIMA_CAÑETE_COAYLLO',
 'LIMA_CAÑETE_IMPERIAL',
 'LIMA_CAÑETE_LUNAHUANA ',
 'LIMA_CAÑETE_MALA',
 'LIMA_CAÑETE_NUEVO IMPERIAL',
 'LIMA_CAÑETE_PACARAN',
 'LIMA_CAÑETE_QUILMANA ',
 'LIMA_CAÑETE_SAN ANTONIO',
 'LIMA_CAÑETE_SAN LUIS',
 'LIMA_CAÑETE_SAN VICENTE DE CANETE',
 'LIMA_CAÑETE_SANTA CRUZ DE FLORES',
 'LIMA_CAÑETE_ZUNIGA',
 'LIMA_HUARAL_LAMPIAN',
 'LIMA_HUARAL_SUMBILCA',
 'LIMA_HUARAL_VEINTISIETE DE NOVIEMBRE',
 'LIMA_HUAROCHIRI_SAN PEDRO DE HUANCAYRE',
 'LIMA_LIMA_MAGDALENA VIEJA',
 'LIMA_YAUYOS_AYAUCA',
 'LIMA_YAUYOS_HUAMPARA',
 'LORETO_DATEM DEL MARAÑON_ANDOAS',
 'LORETO_DATEM DEL MARAÑON_BARRANCA',
 'LORETO_DATEM DEL MARAÑON_CAHUAPANAS',
 'LORETO_DATEM DEL MARAÑON_MANSERICHE',
 'LORETO_DATEM DEL MARAÑON_MORONA',
 'LORETO_DATEM DEL MARAÑON_PASTAZA',
 'LORETO_PUTUMAYO_ROSA PANDURO',
 'LORETO_PUTUMAYO_YAGUAS',
 'LORETO_REQUENA_YAQUERANA',
 'PIURA_SECHURA_RINCONADA-LLICUAR',
 'PUNO_LAMPA_PUCARA ',
 'SAN MARTIN_PICOTA_TRES-UNIDOS',
 'SAN MARTIN_RIOJA_ELIAS SOPLiN VARGAS',
 'SAN MARTIN_SAN MARTIN_PAPA-PLAYA',
 'TACNA_TARATA_ESTIQUE PAMPA',
 'UCAYALI_PURÚS_PURUS'}

In [126]:
from thefuzz.process import extractOne as getBest
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[('APURIMAC_AYMARAES_CARAYBAMBA', ('APURIMAC_AYMARAES_CARAIBAMBA', 96)),
 ('LIMA_CAхTE_SAN VICENTE DE CANETE',
  ('LIMA_CAÑETE_SAN VICENTE DE CANETE', 97)),
 ('SAN MARTIN_PICOTA_TRES UNIDOS', ('SAN MARTIN_PICOTA_TRES-UNIDOS', 100)),
 ('LIMA_CAхTE_ASIA', ('LIMA_CAÑETE_ASIA', 93)),
 ('ICA_NASCA_VISTA ALEGRE', ('ICA_NAZCA_VISTA ALEGRE', 95)),
 ('AYACUCHO_VILCAS HUAMAN_VISCHONGO',
  ('AYACUCHO_VILCAS-HUAMAN_VISCHONGO', 100)),
 ('LORETO_DATEM DEL MARAяN_BARRANCA',
  ('LORETO_DATEM DEL MARAÑON_BARRANCA', 97)),
 ('HUANUCO_HUANUCO_QUISQUI (KICHKI)', ('HUANUCO_HUANUCO_QUISQUI', 95)),
 ('PUNO_LAMPA_PUCARA', ('PUNO_LAMPA_PUCARA ', 100)),
 ('TACNA_TARATA_ESTIQUE-PAMPA', ('TACNA_TARATA_ESTIQUE PAMPA', 100)),
 ('LAMBAYEQUE_FERREсFE_PUEBLO NUEVO',
  ('LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO', 97)),
 ('LA LIBERTAD_GRAN CHIMU_SAYAPULLO',
  ('LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO', 98)),
 ('LA LIBERTAD_VIRU_VIRU', ('LA LIBERTAD_VIRÚ_VIRU', 98)),
 ('LIMA_CAхTE_CHILCA', ('LIMA_CAÑETE_CHILCA', 94)),
 ('AYACUCHO_VILCAS HUAMAN_ACCOMARCA',
  ('AYACUCHO_VILCAS-HUAMAN_ACCOMARCA', 100)),
 ('AYACUCHO_VILCAS HUAMAN_INDEPENDENCIA',
  ('AYACUCHO_VILCAS-HUAMAN_INDEPENDENCIA', 100)),
 ('LIMA_LIMA_PUEBLO LIBRE', ('LIMA_LIMA_MAGDALENA VIEJA', 60)),
 ('APURIMAC_CHINCHEROS_ANCO_HUALLO', ('APURIMAC_CHINCHEROS_ANCO HUALLO', 97)),
 ('AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS',
  ('AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS', 99)),
 ('LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO',
  ('LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO', 98)),
 ('CUSCO_ACOMAYO_SANGARARA', ('CUSCO_ACOMAYO_SANGARARA ', 100)),
 ('LAMBAYEQUE_FERREсFE_CANARIS', ('LAMBAYEQUE_FERREÑAFE_CANARIS', 96)),
 ('LORETO_DATEM DEL MARAяN_MORONA', ('LORETO_DATEM DEL MARAÑON_MORONA', 97)),
 ('HUANUCO_MARAяN_LA MORADA', ('HUANUCO_MARAÑON_LA MORADA', 96)),
 ('ICA_NASCA_EL INGENIO', ('ICA_NAZCA_EL INGENIO', 95)),
 ('AREQUIPA_CAMANA_CAMANA', ('AREQUIPA_CAMANA_CAMANA ', 100)),
 ('LIMA_CAхTE_ZUNIGA', ('LIMA_CAÑETE_ZUNIGA', 94)),
 ('JUNIN_HUANCAYO_PUCARA', ('JUNIN_HUANCAYO_PUCARA ', 100)),
 ('LIMA_CAхTE_NUEVO IMPERIAL', ('LIMA_CAÑETE_NUEVO IMPERIAL', 96)),
 ('ICA_NASCA_NASCA', ('ICA_NAZCA_NAZCA', 87)),
 ('LORETO_DATEM DEL MARAяN_CAHUAPANAS',
  ('LORETO_DATEM DEL MARAÑON_CAHUAPANAS', 97)),
 ('LORETO_DATEM DEL MARAяN_MANSERICHE',
  ('LORETO_DATEM DEL MARAÑON_MANSERICHE', 97)),
 ('HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE',
  ('HUANCAVELICA_ANGARAES_HUALLAY GRANDE', 99)),
 ('LIMA_CAхTE_QUILMANA', ('LIMA_CAÑETE_QUILMANA ', 95)),
 ('LA LIBERTAD_GRAN CHIMU_CASCAS', ('LA LIBERTAD_GRAN CHIMÚ_CASCAS', 98)),
 ('HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA',
  ('HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA', 98)),
 ('LIMA_CAхTE_COAYLLO', ('LIMA_CAÑETE_COAYLLO', 94)),
 ('HUANUCO_MARAяN_CHOLON', ('HUANUCO_MARAÑON_CHOLON', 95)),
 ('LIMA_CAхTE_MALA', ('LIMA_CAÑETE_MALA', 93)),
 ('LIMA_CAхTE_SAN ANTONIO', ('LIMA_CAÑETE_SAN ANTONIO', 95)),
 ('LA LIBERTAD_VIRU_CHAO', ('LA LIBERTAD_VIRÚ_CHAO', 98)),
 ('AYACUCHO_VILCAS HUAMAN_CARHUANCA',
  ('AYACUCHO_VILCAS-HUAMAN_CARHUANCA', 100)),
 ('LIMA_CAхTE_PACARAN', ('LIMA_CAÑETE_PACARAN', 94)),
 ('PIURA_SECHURA_RINCONADA LLICUAR', ('PIURA_SECHURA_RINCONADA-LLICUAR', 100)),
 ('CAJAMARCA_JAEN_PUCARA', ('CAJAMARCA_JAEN_PUCARA ', 100)),
 ('LIMA_CAхTE_CERRO AZUL', ('LIMA_CAÑETE_CERRO AZUL', 95)),
 ('HUANCAVELICA_ANGARAES_HUANCA-HUANCA',
  ('HUANCAVELICA_ANGARAES_HUANCA HUANCA', 100)),
 ('ICA_ICA_SAN JOSE DE LOS MOLINOS', ('ICA_ICA_SAN JOSE DE  LOS MOLINOS', 98)),
 ('JUNIN_YAULI_SANTA BARBARA DE CARHUACAYAN',
  ('JUNIN_YAULI_SANTA BARBARA DE CARHUACAYaN', 100)),
 ('JUNIN_CHUPACA_SAN JUAN DE ISCOS', ('JUNIN_CHUPACA_SAN JUAN DE YSCOS', 97)),
 ('LIMA_CAхTE_SANTA CRUZ DE FLORES', ('LIMA_CAÑETE_SANTA CRUZ DE FLORES', 97)),
 ('AYACUCHO_VILCAS HUAMAN_SAURAMA', ('AYACUCHO_VILCAS-HUAMAN_SAURAMA', 100)),
 ('LAMBAYEQUE_FERREсFE_INCAHUASI', ('LAMBAYEQUE_FERREÑAFE_INCAHUASI', 97)),
 ('UCAYALI_PURUS_PURUS', ('UCAYALI_PURÚS_PURUS', 97)),
 ('LIMA_CAхTE_IMPERIAL', ('LIMA_CAÑETE_IMPERIAL', 95)),
 ('AYACUCHO_VILCAS HUAMAN_VILCAS HUAMAN',
  ('AYACUCHO_VILCAS-HUAMAN_VILCAS HUAMAN', 100)),
 ('LORETO_DATEM DEL MARAяN_ANDOAS', ('LORETO_DATEM DEL MARAÑON_ANDOAS', 97)),
 ('ICA_NASCA_MARCONA', ('ICA_NAZCA_MARCONA', 94)),
 ('SAN MARTIN_RIOJA_ELIAS SOPLIN VARGAS',
  ('SAN MARTIN_RIOJA_ELIAS SOPLiN VARGAS', 100)),
 ('LIMA_YAUYOS_ALLAUCA', ('LIMA_YAUYOS_AYAUCA', 92)),
 ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO',
  ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED', 99)),
 ('HUANUCO_MARAяN_SAN BUENAVENTURA', ('HUANUCO_MARAÑON_SAN BUENAVENTURA', 97)),
 ('AYACUCHO_VILCAS HUAMAN_HUAMBALPA',
  ('AYACUCHO_VILCAS-HUAMAN_HUAMBALPA', 100)),
 ('LIMA_CAхTE_LUNAHUANA', ('LIMA_CAÑETE_LUNAHUANA ', 95)),
 ('LAMBAYEQUE_FERREсFE_PITIPO', ('LAMBAYEQUE_FERREÑAFE_PITIPO', 96)),
 ('LAMBAYEQUE_FERREсFE_FERRENAFE', ('LAMBAYEQUE_FERREÑAFE_FERRENAFE', 97)),
 ('JUNIN_JAUJA_TUNAN MARCA', ('JUNIN_JAUJA_TUNAN-MARCA', 100)),
 ('LA LIBERTAD_GRAN CHIMU_LUCMA', ('LA LIBERTAD_GRAN CHIMÚ_LUCMA', 98)),
 ('SAN MARTIN_SAN MARTIN_PAPAPLAYA', ('SAN MARTIN_SAN MARTIN_PAPA-PLAYA', 98)),
 ('LA LIBERTAD_GRAN CHIMU_MARMOT', ('LA LIBERTAD_GRAN CHIMÚ_MARMOT', 98)),
 ('LIMA_CAхTE_CALANGO', ('LIMA_CAÑETE_CALANGO', 94)),
 ('ICA_NASCA_CHANGUILLO', ('ICA_NAZCA_CHANGUILLO', 95)),
 ('AREQUIPA_CAMANA_MARIANO NICOLAS VALCARCEL',
  ('AREQUIPA_CAMANA_MARIANO NICOLAS VALCaRCEL', 100)),
 ('JUNIN_JAUJA_MASMA CHICCHE', ('JUNIN_JAUJA_MASMA-CHICCHE', 100)),
 ('HUANUCO_MARAяN_HUACRACHUCO', ('HUANUCO_MARAÑON_HUACRACHUCO', 96)),
 ('HUANCAVELICA_CASTROVIRREYNA_TANTARA',
  ('HUANCAVELICA_CASTROVIRREYNA_TANTARA ', 100)),
 ('AYACUCHO_VILCAS HUAMAN_CONCEPCION',
  ('AYACUCHO_VILCAS-HUAMAN_CONCEPCION', 100)),
 ('LIMA_CAхTE_SAN LUIS', ('LIMA_CAÑETE_SAN LUIS', 95)),
 ('LA LIBERTAD_VIRU_GUADALUPITO', ('LA LIBERTAD_VIRÚ_GUADALUPITO', 98)),
 ('LORETO_DATEM DEL MARAяN_PASTAZA', ('LORETO_DATEM DEL MARAÑON_PASTAZA', 97))]

In [127]:
changesDis={getBest(c,onlyDis)[0]:c for c in onlyCrim if getBest(c,onlyDis)[1]==100}
changesDis

{'SAN MARTIN_PICOTA_TRES-UNIDOS': 'SAN MARTIN_PICOTA_TRES UNIDOS',
 'AYACUCHO_VILCAS-HUAMAN_VISCHONGO': 'AYACUCHO_VILCAS HUAMAN_VISCHONGO',
 'PUNO_LAMPA_PUCARA ': 'PUNO_LAMPA_PUCARA',
 'TACNA_TARATA_ESTIQUE PAMPA': 'TACNA_TARATA_ESTIQUE-PAMPA',
 'AYACUCHO_VILCAS-HUAMAN_ACCOMARCA': 'AYACUCHO_VILCAS HUAMAN_ACCOMARCA',
 'AYACUCHO_VILCAS-HUAMAN_INDEPENDENCIA': 'AYACUCHO_VILCAS HUAMAN_INDEPENDENCIA',
 'CUSCO_ACOMAYO_SANGARARA ': 'CUSCO_ACOMAYO_SANGARARA',
 'AREQUIPA_CAMANA_CAMANA ': 'AREQUIPA_CAMANA_CAMANA',
 'JUNIN_HUANCAYO_PUCARA ': 'JUNIN_HUANCAYO_PUCARA',
 'AYACUCHO_VILCAS-HUAMAN_CARHUANCA': 'AYACUCHO_VILCAS HUAMAN_CARHUANCA',
 'PIURA_SECHURA_RINCONADA-LLICUAR': 'PIURA_SECHURA_RINCONADA LLICUAR',
 'CAJAMARCA_JAEN_PUCARA ': 'CAJAMARCA_JAEN_PUCARA',
 'HUANCAVELICA_ANGARAES_HUANCA HUANCA': 'HUANCAVELICA_ANGARAES_HUANCA-HUANCA',
 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYaN': 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYAN',
 'AYACUCHO_VILCAS-HUAMAN_SAURAMA': 'AYACUCHO_VILCAS HUAMAN_SAURAMA',
 'AYACUCHO_VILCAS-HUAMAN_VILCAS HUAMAN': 'AYACUCHO_VILCAS HUAMAN_VILCAS HUAMAN',
 'SAN MARTIN_RIOJA_ELIAS SOPLiN VARGAS': 'SAN MARTIN_RIOJA_ELIAS SOPLIN VARGAS',
 'AYACUCHO_VILCAS-HUAMAN_HUAMBALPA': 'AYACUCHO_VILCAS HUAMAN_HUAMBALPA',
 'JUNIN_JAUJA_TUNAN-MARCA': 'JUNIN_JAUJA_TUNAN MARCA',
 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCaRCEL': 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCARCEL',
 'JUNIN_JAUJA_MASMA-CHICCHE': 'JUNIN_JAUJA_MASMA CHICCHE',
 'HUANCAVELICA_CASTROVIRREYNA_TANTARA ': 'HUANCAVELICA_CASTROVIRREYNA_TANTARA',
 'AYACUCHO_VILCAS-HUAMAN_CONCEPCION': 'AYACUCHO_VILCAS HUAMAN_CONCEPCION'}

In [128]:
dis.replace({'merger':changesDis},inplace=True)

In [129]:
onlyCrim=set(crim.merger) - set(dis.merger)
onlyDis=set(dis.merger)-set(crim.merger)
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[('APURIMAC_AYMARAES_CARAYBAMBA', ('APURIMAC_AYMARAES_CARAIBAMBA', 96)),
 ('LORETO_DATEM DEL MARAяN_MORONA', ('LORETO_DATEM DEL MARAÑON_MORONA', 97)),
 ('HUANUCO_MARAяN_LA MORADA', ('HUANUCO_MARAÑON_LA MORADA', 96)),
 ('ICA_NASCA_EL INGENIO', ('ICA_NAZCA_EL INGENIO', 95)),
 ('LIMA_YAUYOS_ALLAUCA', ('LIMA_YAUYOS_AYAUCA', 92)),
 ('LIMA_CAхTE_SAN VICENTE DE CANETE',
  ('LIMA_CAÑETE_SAN VICENTE DE CANETE', 97)),
 ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO',
  ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED', 99)),
 ('HUANUCO_MARAяN_SAN BUENAVENTURA', ('HUANUCO_MARAÑON_SAN BUENAVENTURA', 97)),
 ('LIMA_CAхTE_ZUNIGA', ('LIMA_CAÑETE_ZUNIGA', 94)),
 ('LIMA_CAхTE_SAN ANTONIO', ('LIMA_CAÑETE_SAN ANTONIO', 95)),
 ('LIMA_CAхTE_ASIA', ('LIMA_CAÑETE_ASIA', 93)),
 ('LA LIBERTAD_VIRU_CHAO', ('LA LIBERTAD_VIRÚ_CHAO', 98)),
 ('LIMA_CAхTE_LUNAHUANA', ('LIMA_CAÑETE_LUNAHUANA ', 95)),
 ('LAMBAYEQUE_FERREсFE_PITIPO', ('LAMBAYEQUE_FERREÑAFE_PITIPO', 96)),
 ('ICA_NASCA_VISTA ALEGRE', ('ICA_NAZCA_VISTA ALEGRE', 95)),
 ('LIMA_CAхTE_NUEVO IMPERIAL', ('LIMA_CAÑETE_NUEVO IMPERIAL', 96)),
 ('LIMA_CAхTE_PACARAN', ('LIMA_CAÑETE_PACARAN', 94)),
 ('LAMBAYEQUE_FERREсFE_FERRENAFE', ('LAMBAYEQUE_FERREÑAFE_FERRENAFE', 97)),
 ('LIMA_CAхTE_CERRO AZUL', ('LIMA_CAÑETE_CERRO AZUL', 95)),
 ('LORETO_DATEM DEL MARAяN_BARRANCA',
  ('LORETO_DATEM DEL MARAÑON_BARRANCA', 97)),
 ('HUANUCO_HUANUCO_QUISQUI (KICHKI)', ('HUANUCO_HUANUCO_QUISQUI', 95)),
 ('ICA_ICA_SAN JOSE DE LOS MOLINOS', ('ICA_ICA_SAN JOSE DE  LOS MOLINOS', 98)),
 ('ICA_NASCA_NASCA', ('ICA_NAZCA_NAZCA', 87)),
 ('LORETO_DATEM DEL MARAяN_CAHUAPANAS',
  ('LORETO_DATEM DEL MARAÑON_CAHUAPANAS', 97)),
 ('JUNIN_CHUPACA_SAN JUAN DE ISCOS', ('JUNIN_CHUPACA_SAN JUAN DE YSCOS', 97)),
 ('LA LIBERTAD_GRAN CHIMU_LUCMA', ('LA LIBERTAD_GRAN CHIMÚ_LUCMA', 98)),
 ('LAMBAYEQUE_FERREсFE_PUEBLO NUEVO',
  ('LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO', 97)),
 ('LORETO_DATEM DEL MARAяN_MANSERICHE',
  ('LORETO_DATEM DEL MARAÑON_MANSERICHE', 97)),
 ('SAN MARTIN_SAN MARTIN_PAPAPLAYA', ('SAN MARTIN_SAN MARTIN_PAPA-PLAYA', 98)),
 ('LA LIBERTAD_GRAN CHIMU_MARMOT', ('LA LIBERTAD_GRAN CHIMÚ_MARMOT', 98)),
 ('LIMA_CAхTE_SANTA CRUZ DE FLORES', ('LIMA_CAÑETE_SANTA CRUZ DE FLORES', 97)),
 ('LIMA_CAхTE_CALANGO', ('LIMA_CAÑETE_CALANGO', 94)),
 ('HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE',
  ('HUANCAVELICA_ANGARAES_HUALLAY GRANDE', 99)),
 ('LIMA_CAхTE_QUILMANA', ('LIMA_CAÑETE_QUILMANA ', 95)),
 ('ICA_NASCA_CHANGUILLO', ('ICA_NAZCA_CHANGUILLO', 95)),
 ('LA LIBERTAD_GRAN CHIMU_CASCAS', ('LA LIBERTAD_GRAN CHIMÚ_CASCAS', 98)),
 ('LA LIBERTAD_GRAN CHIMU_SAYAPULLO',
  ('LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO', 98)),
 ('HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA',
  ('HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA', 98)),
 ('LIMA_CAхTE_COAYLLO', ('LIMA_CAÑETE_COAYLLO', 94)),
 ('LA LIBERTAD_VIRU_VIRU', ('LA LIBERTAD_VIRÚ_VIRU', 98)),
 ('LIMA_CAхTE_CHILCA', ('LIMA_CAÑETE_CHILCA', 94)),
 ('LAMBAYEQUE_FERREсFE_INCAHUASI', ('LAMBAYEQUE_FERREÑAFE_INCAHUASI', 97)),
 ('UCAYALI_PURUS_PURUS', ('UCAYALI_PURÚS_PURUS', 97)),
 ('HUANUCO_MARAяN_CHOLON', ('HUANUCO_MARAÑON_CHOLON', 95)),
 ('HUANUCO_MARAяN_HUACRACHUCO', ('HUANUCO_MARAÑON_HUACRACHUCO', 96)),
 ('ICA_NASCA_MARCONA', ('ICA_NAZCA_MARCONA', 94)),
 ('LIMA_LIMA_PUEBLO LIBRE', ('LIMA_LIMA_MAGDALENA VIEJA', 60)),
 ('APURIMAC_CHINCHEROS_ANCO_HUALLO', ('APURIMAC_CHINCHEROS_ANCO HUALLO', 97)),
 ('LIMA_CAхTE_MALA', ('LIMA_CAÑETE_MALA', 93)),
 ('LIMA_CAхTE_SAN LUIS', ('LIMA_CAÑETE_SAN LUIS', 95)),
 ('LIMA_CAхTE_IMPERIAL', ('LIMA_CAÑETE_IMPERIAL', 95)),
 ('LA LIBERTAD_VIRU_GUADALUPITO', ('LA LIBERTAD_VIRÚ_GUADALUPITO', 98)),
 ('AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS',
  ('AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS', 99)),
 ('LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO',
  ('LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO', 98)),
 ('LORETO_DATEM DEL MARAяN_PASTAZA', ('LORETO_DATEM DEL MARAÑON_PASTAZA', 97)),
 ('LORETO_DATEM DEL MARAяN_ANDOAS', ('LORETO_DATEM DEL MARAÑON_ANDOAS', 97)),
 ('LAMBAYEQUE_FERREсFE_CANARIS', ('LAMBAYEQUE_FERREÑAFE_CANARIS', 96))]

In [130]:
changesCrim={c:getBest(c,onlyDis)[0] for c in onlyCrim if getBest(c,onlyDis)[1]>=90}
changesCrim

{'APURIMAC_AYMARAES_CARAYBAMBA': 'APURIMAC_AYMARAES_CARAIBAMBA',
 'LORETO_DATEM DEL MARAяN_MORONA': 'LORETO_DATEM DEL MARAÑON_MORONA',
 'HUANUCO_MARAяN_LA MORADA': 'HUANUCO_MARAÑON_LA MORADA',
 'ICA_NASCA_EL INGENIO': 'ICA_NAZCA_EL INGENIO',
 'LIMA_YAUYOS_ALLAUCA': 'LIMA_YAUYOS_AYAUCA',
 'LIMA_CAхTE_SAN VICENTE DE CANETE': 'LIMA_CAÑETE_SAN VICENTE DE CANETE',
 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO': 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED',
 'HUANUCO_MARAяN_SAN BUENAVENTURA': 'HUANUCO_MARAÑON_SAN BUENAVENTURA',
 'LIMA_CAхTE_ZUNIGA': 'LIMA_CAÑETE_ZUNIGA',
 'LIMA_CAхTE_SAN ANTONIO': 'LIMA_CAÑETE_SAN ANTONIO',
 'LIMA_CAхTE_ASIA': 'LIMA_CAÑETE_ASIA',
 'LA LIBERTAD_VIRU_CHAO': 'LA LIBERTAD_VIRÚ_CHAO',
 'LIMA_CAхTE_LUNAHUANA': 'LIMA_CAÑETE_LUNAHUANA ',
 'LAMBAYEQUE_FERREсFE_PITIPO': 'LAMBAYEQUE_FERREÑAFE_PITIPO',
 'ICA_NASCA_VISTA ALEGRE': 'ICA_NAZCA_VISTA ALEGRE',
 'LIMA_CAхTE_NUEVO IMPERIAL': 'LIMA_CAÑETE_NUEVO IMPERIAL',
 'LIMA_CAхTE_PACARAN': 'LIMA_CAÑETE_PACARAN',
 'LAMBAYEQUE_FERREсFE_FERRENAFE': 'LAMBAYEQUE_FERREÑAFE_FERRENAFE',
 'LIMA_CAхTE_CERRO AZUL': 'LIMA_CAÑETE_CERRO AZUL',
 'LORETO_DATEM DEL MARAяN_BARRANCA': 'LORETO_DATEM DEL MARAÑON_BARRANCA',
 'HUANUCO_HUANUCO_QUISQUI (KICHKI)': 'HUANUCO_HUANUCO_QUISQUI',
 'ICA_ICA_SAN JOSE DE LOS MOLINOS': 'ICA_ICA_SAN JOSE DE  LOS MOLINOS',
 'LORETO_DATEM DEL MARAяN_CAHUAPANAS': 'LORETO_DATEM DEL MARAÑON_CAHUAPANAS',
 'JUNIN_CHUPACA_SAN JUAN DE ISCOS': 'JUNIN_CHUPACA_SAN JUAN DE YSCOS',
 'LA LIBERTAD_GRAN CHIMU_LUCMA': 'LA LIBERTAD_GRAN CHIMÚ_LUCMA',
 'LAMBAYEQUE_FERREсFE_PUEBLO NUEVO': 'LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO',
 'LORETO_DATEM DEL MARAяN_MANSERICHE': 'LORETO_DATEM DEL MARAÑON_MANSERICHE',
 'SAN MARTIN_SAN MARTIN_PAPAPLAYA': 'SAN MARTIN_SAN MARTIN_PAPA-PLAYA',
 'LA LIBERTAD_GRAN CHIMU_MARMOT': 'LA LIBERTAD_GRAN CHIMÚ_MARMOT',
 'LIMA_CAхTE_SANTA CRUZ DE FLORES': 'LIMA_CAÑETE_SANTA CRUZ DE FLORES',
 'LIMA_CAхTE_CALANGO': 'LIMA_CAÑETE_CALANGO',
 'HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE': 'HUANCAVELICA_ANGARAES_HUALLAY GRANDE',
 'LIMA_CAхTE_QUILMANA': 'LIMA_CAÑETE_QUILMANA ',
 'ICA_NASCA_CHANGUILLO': 'ICA_NAZCA_CHANGUILLO',
 'LA LIBERTAD_GRAN CHIMU_CASCAS': 'LA LIBERTAD_GRAN CHIMÚ_CASCAS',
 'LA LIBERTAD_GRAN CHIMU_SAYAPULLO': 'LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO',
 'HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA': 'HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA',
 'LIMA_CAхTE_COAYLLO': 'LIMA_CAÑETE_COAYLLO',
 'LA LIBERTAD_VIRU_VIRU': 'LA LIBERTAD_VIRÚ_VIRU',
 'LIMA_CAхTE_CHILCA': 'LIMA_CAÑETE_CHILCA',
 'LAMBAYEQUE_FERREсFE_INCAHUASI': 'LAMBAYEQUE_FERREÑAFE_INCAHUASI',
 'UCAYALI_PURUS_PURUS': 'UCAYALI_PURÚS_PURUS',
 'HUANUCO_MARAяN_CHOLON': 'HUANUCO_MARAÑON_CHOLON',
 'HUANUCO_MARAяN_HUACRACHUCO': 'HUANUCO_MARAÑON_HUACRACHUCO',
 'ICA_NASCA_MARCONA': 'ICA_NAZCA_MARCONA',
 'APURIMAC_CHINCHEROS_ANCO_HUALLO': 'APURIMAC_CHINCHEROS_ANCO HUALLO',
 'LIMA_CAхTE_MALA': 'LIMA_CAÑETE_MALA',
 'LIMA_CAхTE_SAN LUIS': 'LIMA_CAÑETE_SAN LUIS',
 'LIMA_CAхTE_IMPERIAL': 'LIMA_CAÑETE_IMPERIAL',
 'LA LIBERTAD_VIRU_GUADALUPITO': 'LA LIBERTAD_VIRÚ_GUADALUPITO',
 'AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS': 'AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS',
 'LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO': 'LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO',
 'LORETO_DATEM DEL MARAяN_PASTAZA': 'LORETO_DATEM DEL MARAÑON_PASTAZA',
 'LORETO_DATEM DEL MARAяN_ANDOAS': 'LORETO_DATEM DEL MARAÑON_ANDOAS',
 'LAMBAYEQUE_FERREсFE_CANARIS': 'LAMBAYEQUE_FERREÑAFE_CANARIS'}

In [131]:
crim.replace({'merger':changesCrim},inplace=True)
onlyCrim=set(crim.merger) - set(dis.merger)
onlyDis=set(dis.merger)-set(crim.merger)
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[('LIMA_LIMA_PUEBLO LIBRE', ('LIMA_LIMA_MAGDALENA VIEJA', 60)),
 ('ICA_NASCA_NASCA', ('ICA_NAZCA_NAZCA', 87))]

In [132]:
handy={'LIMA_LIMA_MAGDALENA VIEJA':'LIMA_LIMA_PUEBLO LIBRE','ICA_NAZCA_NAZCA':'ICA_NASCA_NASCA'}
dis.replace({'merger':handy},inplace=True)
onlyCrim=set(crim.merger) - set(dis.merger)
onlyDis=set(dis.merger)-set(crim.merger)
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[]

In [135]:
dis.merge(crim,on='merger',how='left')

,DEPARTAMEN,PROVINCIA,DISTRITO,INSTITUCIO,geometry,merger,dep,prov,cod,distrito,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,TACNA,TACNA,CORONEL GREGORIO ALBARRACIN LANCHIPA,IGN,"POLYGON ((-70.17413 -18.12896, -70.17461 -18.1...",TACNA_TACNA_CORONEL GREGORIO ALBARRACIN LANCHIPA,TACNA,TACNA,230110,CORONEL GREGORIO ALBARRACIN LANCHIPA,532,609,684,852,1 033,755,1 015,974,1 098,781
1,TACNA,TACNA,POCOLLAY,IGN,"POLYGON ((-69.93475 -17.92557, -69.90467 -17.9...",TACNA_TACNA_POCOLLAY,TACNA,TACNA,230108,POCOLLAY,107,113,225,409,545,431,357,452,521,285
2,TACNA,TACNA,CALANA,IGN,"POLYGON ((-70.11604 -17.91106, -70.11457 -17.9...",TACNA_TACNA_CALANA,TACNA,TACNA,230103,CALANA,1,4,68,9,12,44,77,97,146,82
3,TACNA,TACNA,TACNA,IGN,"POLYGON ((-70.31490 -17.94498, -70.30682 -17.9...",TACNA_TACNA_TACNA,TACNA,TACNA,230101,TACNA,1 792,1 994,2 152,2 736,2 963,2 143,2 767,3 417,3 206,2 461
4,TACNA,TACNA,SAMA,IGN,"POLYGON ((-70.42497 -17.88934, -70.48022 -17.9...",TACNA_TACNA_SAMA,TACNA,TACNA,230109,SAMA,76,53,72,130,29,14,69,123,98,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1869,LIMA,LIMA,CIENEGUILLA,IGN,"POLYGON ((-76.72917 -11.99948, -76.72596 -11.9...",LIMA_LIMA_CIENEGUILLA,LIMA,LIMA,150109,CIENEGUILLA,296,270,296,351,380,252,329,340,534,525
1870,LIMA,LIMA,ANCON,IGN,"POLYGON ((-77.06501 -11.57523, -77.06499 -11.5...",LIMA_LIMA_ANCON,LIMA,LIMA,150102,ANCON,710,651,645,661,853,736,772,1 039,1 255,1 043
1871,LIMA,LIMA,CARABAYLLO,IGN,"POLYGON ((-76.89892 -11.72963, -76.89768 -11.7...",LIMA_LIMA_CARABAYLLO,LIMA,LIMA,150106,CARABAYLLO,3 510,3 129,3 870,3 994,5 158,3 785,4 012,4 724,4 695,4 526
1872,CALLAO,CALLAO,MI PERU,IGN,"POLYGON ((-77.11491 -11.84189, -77.11450 -11.8...",CALLAO_CALLAO_MI PERU,CALLAO,CALLAO,070107,MI PERU,126,491,466,514,512,211,290,276,387,145
1873,LIMA,LIMA,SANTIAGO DE SURCO,IGN,"POLYGON ((-76.95742 -12.07604, -76.95741 -12.0...",LIMA_LIMA_SANTIAGO DE SURCO,LIMA,LIMA,150140,SANTIAGO DE SURCO,6 145,5 729,7 388,8 780,7 861,4 741,5 946,6 487,7 761,7 808