In [54]:
import pandas as pd


link="https://github.com/PoliticayGobiernoPUCP/Gob_TomaDeDecisiones/raw/refs/heads/master/dataCrim.xlsx"
crim=pd.read_excel(link,dtype={'cod': str})
crim.head()

,dep,prov,cod,distrito,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,AMAZONAS,BAGUA,010201,BAGUA,247,193,50,19,109,61,71,91,64,75
1,AMAZONAS,NaN,010202,ARAMANGO,16,36,50,65,70,35,51,65,48,29
2,AMAZONAS,NaN,010203,COPALLIN,1,23,54,60,51,47,27,17,23,34
3,AMAZONAS,NaN,010204,EL PARCO,2,1,NaN,4,5,5,10,4,33,8
4,AMAZONAS,NaN,010205,IMAZA,58,72,58,92,115,100,138,101,74,82

In [59]:
crim['prov']=crim.prov.ffill()

In [60]:
crim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1858 entries, 0 to 1857
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   dep       1858 non-null   object
 1   prov      1858 non-null   object
 2   cod       1858 non-null   object
 3   distrito  1856 non-null   object
 4   2015      1509 non-null   object
 5   2016      1516 non-null   object
 6   2017      1633 non-null   object
 7   2018      1600 non-null   object
 8   2019      1505 non-null   object
 9   2020      1590 non-null   object
 10  2021      1667 non-null   object
 11  2022      1668 non-null   object
 12  2023      1671 non-null   object
 13  2024      1617 non-null   object
dtypes: object(14)
memory usage: 203.3+ KB

In [94]:
crim.replace({'dep':{'LIMA METROPOLITANA':'LIMA'}},inplace=True)

In [97]:
import geopandas as gpd

dis=gpd.read_file('DISTRITOS1874.shp')
dis.head()

,DEPARTAMEN,PROVINCIA,DISTRITO,INSTITUCIO,geometry
0,TACNA,TACNA,CORONEL GREGORIO ALBARRACIN LANCHIPA,IGN,"POLYGON ((-70.17413 -18.12896, -70.17461 -18.1..."
1,TACNA,TACNA,POCOLLAY,IGN,"POLYGON ((-69.93475 -17.92557, -69.90467 -17.9..."
2,TACNA,TACNA,CALANA,IGN,"POLYGON ((-70.11604 -17.91106, -70.11457 -17.9..."
3,TACNA,TACNA,TACNA,IGN,"POLYGON ((-70.31490 -17.94498, -70.30682 -17.9..."
4,TACNA,TACNA,SAMA,IGN,"POLYGON ((-70.42497 -17.88934, -70.48022 -17.9..."

In [114]:
from unidecode import unidecode

# dis['DISTRITO']=dis.DISTRITO.apply(unidecode)
# crim['distrito']=

# crim.distrito.apply(str).apply(unidecode)

for e in crim.distrito:
    try:
        unidecode(e)
    except:
        print(e)

nan
nan

In [77]:
colsCrim=['dep','prov','distrito']
colsDis=['DEPARTAMEN','PROVINCIA','DISTRITO']
concatRowVals=lambda row: '_'.join(row.values.astype(str))
crim['merger']=crim[colsCrim].apply(concatRowVals, axis=1)
dis['merger']=dis[colsDis].apply(concatRowVals, axis=1)

In [79]:
onlyCrim=set(crim.merger) - set(dis.merger)
onlyCrim

{'ANCASH_SANTA_CACERES DEL PERU',
 'APURIMAC_AYMARAES_CARAYBAMBA',
 'APURIMAC_CHINCHEROS_ANCO_HUALLO',
 'AREQUIPA_CAMANA_CAMANA',
 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCARCEL',
 'AYACUCHO_HUAMANGA_JESUS NAZARENO',
 'AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS',
 'AYACUCHO_VILCAS HUAMAN_ACCOMARCA',
 'AYACUCHO_VILCAS HUAMAN_CARHUANCA',
 'AYACUCHO_VILCAS HUAMAN_CONCEPCION',
 'AYACUCHO_VILCAS HUAMAN_HUAMBALPA',
 'AYACUCHO_VILCAS HUAMAN_INDEPENDENCIA',
 'AYACUCHO_VILCAS HUAMAN_SAURAMA',
 'AYACUCHO_VILCAS HUAMAN_VILCAS HUAMAN',
 'AYACUCHO_VILCAS HUAMAN_VISCHONGO',
 'CAJAMARCA_CAJAMARCA_JESUS',
 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO',
 'CAJAMARCA_JAEN_PUCARA',
 'CUSCO_ACOMAYO_SANGARARA',
 'CUSCO_CANAS_TUPAC AMARU',
 'HUANCAVELICA_ANGARAES_HUANCA-HUANCA',
 'HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE',
 'HUANCAVELICA_CASTROVIRREYNA_TANTARA',
 'HUANUCO_HUANUCO_QUISQUI (KICHKI)',
 'HUANUCO_LAURICOCHA_JESUS',
 'HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAUN',
 'HUANUCO_MARAяN_CHOLON',
 'HUANUCO_MARAяN_HUACRACHUCO',
 'HUANUCO_MARAяN_LA MORADA',
 'HUANUCO_MARAяN_SAN BUENAVENTURA',
 'HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA',
 'ICA_ICA_PACHACUTEC',
 'ICA_ICA_SAN JOSE DE LOS MOLINOS',
 'ICA_NASCA_CHANGUILLO',
 'ICA_NASCA_EL INGENIO',
 'ICA_NASCA_MARCONA',
 'ICA_NASCA_NASCA',
 'ICA_NASCA_VISTA ALEGRE',
 'ICA_PISCO_TUPAC AMARU INCA',
 'JUNIN_CHUPACA_SAN JUAN DE ISCOS',
 'JUNIN_HUANCAYO_PUCARA',
 'JUNIN_JAUJA_MASMA CHICCHE',
 'JUNIN_JAUJA_TUNAN MARCA',
 'JUNIN_SATIPO_VIZCATÁN DEL ENE',
 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYAN',
 'LA LIBERTAD_GRAN CHIMU_CASCAS',
 'LA LIBERTAD_GRAN CHIMU_LUCMA',
 'LA LIBERTAD_GRAN CHIMU_MARMOT',
 'LA LIBERTAD_GRAN CHIMU_SAYAPULLO',
 'LA LIBERTAD_VIRU_CHAO',
 'LA LIBERTAD_VIRU_GUADALUPITO',
 'LA LIBERTAD_VIRU_VIRU',
 'LAMBAYEQUE_CHICLAYO_MONSEFU',
 'LAMBAYEQUE_CHICLAYO_OYOTUN',
 'LAMBAYEQUE_FERREсFE_CAÑARIS',
 'LAMBAYEQUE_FERREсFE_FERREÑAFE',
 'LAMBAYEQUE_FERREсFE_INCAHUASI',
 'LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO',
 'LAMBAYEQUE_FERREсFE_PITIPO',
 'LAMBAYEQUE_FERREсFE_PUEBLO NUEVO',
 'LAMBAYEQUE_LAMBAYEQUE_TUCUME',
 'LIMA METROPOLITANA_LIMA_ANCON',
 'LIMA METROPOLITANA_LIMA_ATE',
 'LIMA METROPOLITANA_LIMA_BARRANCO',
 'LIMA METROPOLITANA_LIMA_BREÑA',
 'LIMA METROPOLITANA_LIMA_CARABAYLLO',
 'LIMA METROPOLITANA_LIMA_CHACLACAYO',
 'LIMA METROPOLITANA_LIMA_CHORRILLOS',
 'LIMA METROPOLITANA_LIMA_CIENEGUILLA',
 'LIMA METROPOLITANA_LIMA_COMAS',
 'LIMA METROPOLITANA_LIMA_EL AGUSTINO',
 'LIMA METROPOLITANA_LIMA_INDEPENDENCIA',
 'LIMA METROPOLITANA_LIMA_JESUS MARIA',
 'LIMA METROPOLITANA_LIMA_LA MOLINA',
 'LIMA METROPOLITANA_LIMA_LA VICTORIA',
 'LIMA METROPOLITANA_LIMA_LIMA',
 'LIMA METROPOLITANA_LIMA_LINCE',
 'LIMA METROPOLITANA_LIMA_LOS OLIVOS',
 'LIMA METROPOLITANA_LIMA_LURIGANCHO',
 'LIMA METROPOLITANA_LIMA_LURIN',
 'LIMA METROPOLITANA_LIMA_MAGDALENA DEL MAR',
 'LIMA METROPOLITANA_LIMA_MIRAFLORES',
 'LIMA METROPOLITANA_LIMA_PACHACAMAC',
 'LIMA METROPOLITANA_LIMA_PUCUSANA',
 'LIMA METROPOLITANA_LIMA_PUEBLO LIBRE',
 'LIMA METROPOLITANA_LIMA_PUENTE PIEDRA',
 'LIMA METROPOLITANA_LIMA_PUNTA HERMOSA',
 'LIMA METROPOLITANA_LIMA_PUNTA NEGRA',
 'LIMA METROPOLITANA_LIMA_RIMAC',
 'LIMA METROPOLITANA_LIMA_SAN BARTOLO',
 'LIMA METROPOLITANA_LIMA_SAN BORJA',
 'LIMA METROPOLITANA_LIMA_SAN ISIDRO',
 'LIMA METROPOLITANA_LIMA_SAN JUAN DE LURIGANCHO',
 'LIMA METROPOLITANA_LIMA_SAN JUAN DE MIRAFLORES',
 'LIMA METROPOLITANA_LIMA_SAN LUIS',
 'LIMA METROPOLITANA_LIMA_SAN MARTIN DE PORRES',
 'LIMA METROPOLITANA_LIMA_SAN MIGUEL',
 'LIMA METROPOLITANA_LIMA_SANTA ANITA',
 'LIMA METROPOLITANA_LIMA_SANTA MARIA DEL MAR',
 'LIMA METROPOLITANA_LIMA_SANTA ROSA',
 'LIMA METROPOLITANA_LIMA_SANTIAGO DE SURCO',
 'LIMA METROPOLITANA_LIMA_SURQUILLO',
 'LIMA METROPOLITANA_LIMA_VILLA EL SALVADOR',
 'LIMA METROPOLITANA_LIMA_VILLA MARIA DEL TRIUNFO',
 'LIMA_CAхTE_ASIA',
 'LIMA_CAхTE_CALANGO',
 'LIMA_CAхTE_CERRO AZUL',
 'LIMA_CAхTE_CHILCA',
 'LIMA_CAхTE_COAYLLO',
 'LIMA_CAхTE_IMPERIAL',
 'LIMA_CAхTE_LUNAHUANA',
 'LIMA_CAхTE_MALA',
 'LIMA_CAхTE_NUEVO IMPERIAL',
 'LIMA_CAхTE_PACARAN',
 'LIMA_CAхTE_QUILMANA',
 'LIMA_CAхTE_SAN ANTONIO',
 'LIMA_CAхTE_SAN LUIS',
 'LIMA_CAхTE_SAN VICENTE DE CAÑETE',
 'LIMA_CAхTE_SANTA CRUZ DE FLORES',
 'LIMA_CAхTE_ZUÑIGA',
 'LIMA_YAUYOS_ALLAUCA',
 'LORETO_DATEM DEL MARAяN_ANDOAS',
 'LORETO_DATEM DEL MARAяN_BARRANCA',
 'LORETO_DATEM DEL MARAяN_CAHUAPANAS',
 'LORETO_DATEM DEL MARAяN_MANSERICHE',
 'LORETO_DATEM DEL MARAяN_MORONA',
 'LORETO_DATEM DEL MARAяN_PASTAZA',
 'PASCO_OXAPAMPA_PUERTO BERMUDEZ',
 'PIURA_SECHURA_RINCONADA LLICUAR',
 'PUNO_LAMPA_PUCARA',
 'SAN MARTIN_PICOTA_TRES UNIDOS',
 'SAN MARTIN_RIOJA_ELIAS SOPLIN VARGAS',
 'SAN MARTIN_SAN MARTIN_PAPAPLAYA',
 'TACNA_TARATA_ESTIQUE-PAMPA',
 'UCAYALI_ATALAYA_YURUA',
 'UCAYALI_PADRE ABAD_nan',
 'UCAYALI_PURUS_nan'}

In [80]:
onlyDis=set(dis.merger)-set(crim.merger)
onlyDis

{'ANCASH_AIJA_HUACLLAN',
 'ANCASH_BOLOGNESI_CANIS',
 'ANCASH_SANTA_CACERES DEL PERÚ',
 'APURIMAC_AYMARAES_CARAIBAMBA',
 'APURIMAC_CHINCHEROS_ANCO HUALLO',
 'APURIMAC_CHINCHEROS_EL PORVENIR',
 'APURIMAC_CHINCHEROS_LOS CHANKAS',
 'AREQUIPA_CAMANA_CAMANA\xa0',
 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCáRCEL',
 'AYACUCHO_HUAMANGA_JESÚS NAZARENO',
 'AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS',
 'AYACUCHO_LA MAR_ORONCCOY',
 'AYACUCHO_VILCAS-HUAMAN_ACCOMARCA',
 'AYACUCHO_VILCAS-HUAMAN_CARHUANCA',
 'AYACUCHO_VILCAS-HUAMAN_CONCEPCION',
 'AYACUCHO_VILCAS-HUAMAN_HUAMBALPA',
 'AYACUCHO_VILCAS-HUAMAN_INDEPENDENCIA',
 'AYACUCHO_VILCAS-HUAMAN_SAURAMA',
 'AYACUCHO_VILCAS-HUAMAN_VILCAS HUAMAN',
 'AYACUCHO_VILCAS-HUAMAN_VISCHONGO',
 'CAJAMARCA_CAJAMARCA_JESÚS',
 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED',
 'CAJAMARCA_JAEN_PUCARA\xa0',
 'CUSCO_ACOMAYO_SANGARARA\xa0',
 'CUSCO_CANAS_TÚPAC AMARU',
 'HUANCAVELICA_ANGARAES_HUALLAY GRANDE',
 'HUANCAVELICA_ANGARAES_HUANCA HUANCA',
 'HUANCAVELICA_CASTROVIRREYNA_TANTARA\xa0',
 'HUANCAVELICA_HUAYTARA_SAN ISIDRO',
 'HUANCAVELICA_TAYACAJA_SANTIAGO DE TUCUMA',
 'HUANUCO_HUANUCO_QUISQUI',
 'HUANUCO_LAURICOCHA_JESÚS',
 'HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAÚN',
 'HUANUCO_MARAÑON_CHOLON',
 'HUANUCO_MARAÑON_HUACRACHUCO',
 'HUANUCO_MARAÑON_LA MORADA',
 'HUANUCO_MARAÑON_SAN BUENAVENTURA',
 'HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA',
 'ICA_ICA_PACHACÚTEC',
 'ICA_ICA_SAN JOSE DE  LOS MOLINOS',
 'ICA_NAZCA_CHANGUILLO',
 'ICA_NAZCA_EL INGENIO',
 'ICA_NAZCA_MARCONA',
 'ICA_NAZCA_NAZCA',
 'ICA_NAZCA_VISTA ALEGRE',
 'ICA_PISCO_TÚPAC AMARU INCA',
 'JUNIN_CHUPACA_SAN JUAN DE YSCOS',
 'JUNIN_HUANCAYO_PUCARA\xa0',
 'JUNIN_JAUJA_MASMA-CHICCHE',
 'JUNIN_JAUJA_TUNAN-MARCA',
 'JUNIN_SATIPO_VIZCATAN DEL ENE',
 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYáN',
 'LA LIBERTAD_GRAN CHIMÚ_CASCAS',
 'LA LIBERTAD_GRAN CHIMÚ_LUCMA',
 'LA LIBERTAD_GRAN CHIMÚ_MARMOT',
 'LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO',
 'LA LIBERTAD_VIRÚ_CHAO',
 'LA LIBERTAD_VIRÚ_GUADALUPITO',
 'LA LIBERTAD_VIRÚ_VIRÚ',
 'LAMBAYEQUE_CHICLAYO_MONSEFÚ',
 'LAMBAYEQUE_CHICLAYO_OYOTÚN',
 'LAMBAYEQUE_FERREÑAFE_CAÑARIS',
 'LAMBAYEQUE_FERREÑAFE_FERREÑAFE',
 'LAMBAYEQUE_FERREÑAFE_INCAHUASI',
 'LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO',
 'LAMBAYEQUE_FERREÑAFE_PITIPO',
 'LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO',
 'LAMBAYEQUE_LAMBAYEQUE_TÚCUME',
 'LIMA_CAJATAMBO_COPA',
 'LIMA_CAÑETE_ASIA',
 'LIMA_CAÑETE_CALANGO',
 'LIMA_CAÑETE_CERRO AZUL',
 'LIMA_CAÑETE_CHILCA',
 'LIMA_CAÑETE_COAYLLO',
 'LIMA_CAÑETE_IMPERIAL',
 'LIMA_CAÑETE_LUNAHUANA\xa0',
 'LIMA_CAÑETE_MALA',
 'LIMA_CAÑETE_NUEVO IMPERIAL',
 'LIMA_CAÑETE_PACARAN',
 'LIMA_CAÑETE_QUILMANA\xa0',
 'LIMA_CAÑETE_SAN ANTONIO',
 'LIMA_CAÑETE_SAN LUIS',
 'LIMA_CAÑETE_SAN VICENTE DE CAÑETE',
 'LIMA_CAÑETE_SANTA CRUZ DE FLORES',
 'LIMA_CAÑETE_ZÚÑIGA',
 'LIMA_HUARAL_LAMPIAN',
 'LIMA_HUARAL_SUMBILCA',
 'LIMA_HUARAL_VEINTISIETE DE NOVIEMBRE',
 'LIMA_HUAROCHIRI_SAN PEDRO DE HUANCAYRE',
 'LIMA_LIMA_ANCON',
 'LIMA_LIMA_ATE',
 'LIMA_LIMA_BARRANCO',
 'LIMA_LIMA_BREÑA',
 'LIMA_LIMA_CARABAYLLO',
 'LIMA_LIMA_CHACLACAYO',
 'LIMA_LIMA_CHORRILLOS',
 'LIMA_LIMA_CIENEGUILLA',
 'LIMA_LIMA_COMAS',
 'LIMA_LIMA_EL AGUSTINO',
 'LIMA_LIMA_INDEPENDENCIA',
 'LIMA_LIMA_JESUS MARIA',
 'LIMA_LIMA_LA MOLINA',
 'LIMA_LIMA_LA VICTORIA',
 'LIMA_LIMA_LIMA',
 'LIMA_LIMA_LINCE',
 'LIMA_LIMA_LOS OLIVOS',
 'LIMA_LIMA_LURIGANCHO',
 'LIMA_LIMA_LURIN',
 'LIMA_LIMA_MAGDALENA DEL MAR',
 'LIMA_LIMA_MAGDALENA VIEJA',
 'LIMA_LIMA_MIRAFLORES',
 'LIMA_LIMA_PACHACAMAC',
 'LIMA_LIMA_PUCUSANA',
 'LIMA_LIMA_PUENTE PIEDRA',
 'LIMA_LIMA_PUNTA HERMOSA',
 'LIMA_LIMA_PUNTA NEGRA',
 'LIMA_LIMA_RIMAC',
 'LIMA_LIMA_SAN BARTOLO',
 'LIMA_LIMA_SAN BORJA',
 'LIMA_LIMA_SAN ISIDRO',
 'LIMA_LIMA_SAN JUAN DE LURIGANCHO',
 'LIMA_LIMA_SAN JUAN DE MIRAFLORES',
 'LIMA_LIMA_SAN LUIS',
 'LIMA_LIMA_SAN MARTIN DE PORRES',
 'LIMA_LIMA_SAN MIGUEL',
 'LIMA_LIMA_SANTA ANITA',
 'LIMA_LIMA_SANTA MARIA DEL MAR',
 'LIMA_LIMA_SANTA ROSA',
 'LIMA_LIMA_SANTIAGO DE SURCO',
 'LIMA_LIMA_SURQUILLO',
 'LIMA_LIMA_VILLA EL SALVADOR',
 'LIMA_LIMA_VILLA MARIA DEL TRIUNFO',
 'LIMA_YAUYOS_AYAUCA',
 'LIMA_YAUYOS_HUAMPARA',
 'LORETO_DATEM DEL MARAÑON_ANDOAS',
 'LORETO_DATEM DEL MARAÑON_BARRANCA',
 'LORETO_DATEM DEL MARAÑON_CAHUAPANAS',
 'LORETO_DATEM DEL MARAÑON_MANSERICHE',
 'LORETO_DATEM DEL MARAÑON_MORONA',
 'LORETO_DATEM DEL MARAÑON_PASTAZA',
 'LORETO_PUTUMAYO_ROSA PANDURO',
 'LORETO_PUTUMAYO_YAGUAS',
 'LORETO_REQUENA_YAQUERANA',
 'PASCO_OXAPAMPA_PUERTO BERMÚDEZ',
 'PIURA_SECHURA_RINCONADA-LLICUAR',
 'PUNO_LAMPA_PUCARA\xa0',
 'SAN MARTIN_PICOTA_TRES-UNIDOS',
 'SAN MARTIN_RIOJA_ELIAS SOPLíN VARGAS',
 'SAN MARTIN_SAN MARTIN_PAPA-PLAYA',
 'TACNA_TARATA_ESTIQUE PAMPA',
 'UCAYALI_ATALAYA_YURÚA',
 'UCAYALI_PADRE ABAD_ALEXANDER VON HUMBOLDT',
 'UCAYALI_PURÚS_PURÚS'}

In [81]:
from thefuzz.process import extractOne as getBest
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[('APURIMAC_AYMARAES_CARAYBAMBA', ('APURIMAC_AYMARAES_CARAIBAMBA', 96)),
 ('LIMA METROPOLITANA_LIMA_JESUS MARIA', ('LIMA_LIMA_JESUS MARIA', 86)),
 ('UCAYALI_ATALAYA_YURUA', ('UCAYALI_ATALAYA_YURÚA', 98)),
 ('LIMA METROPOLITANA_LIMA_CHORRILLOS', ('LIMA_LIMA_CHORRILLOS', 76)),
 ('LIMA METROPOLITANA_LIMA_PUEBLO LIBRE', ('LIMA_LIMA_LINCE', 57)),
 ('SAN MARTIN_PICOTA_TRES UNIDOS', ('SAN MARTIN_PICOTA_TRES-UNIDOS', 100)),
 ('LIMA METROPOLITANA_LIMA_SANTA ANITA', ('LIMA_LIMA_SANTA ANITA', 86)),
 ('LIMA_CAхTE_SAN VICENTE DE CAÑETE',
  ('LIMA_CAÑETE_SAN VICENTE DE CAÑETE', 97)),
 ('LIMA_CAхTE_ASIA', ('LIMA_CAÑETE_ASIA', 93)),
 ('LIMA METROPOLITANA_LIMA_PUENTE PIEDRA', ('LIMA_LIMA_PUENTE PIEDRA', 86)),
 ('ICA_NASCA_VISTA ALEGRE', ('ICA_NAZCA_VISTA ALEGRE', 95)),
 ('LIMA METROPOLITANA_LIMA_SANTA ROSA', ('LIMA_LIMA_SANTA ROSA', 86)),
 ('AYACUCHO_VILCAS HUAMAN_VISCHONGO',
  ('AYACUCHO_VILCAS-HUAMAN_VISCHONGO', 100)),
 ('LORETO_DATEM DEL MARAяN_BARRANCA',
  ('LORETO_DATEM DEL MARAÑON_BARRANCA', 97)),
 ('HUANUCO_HUANUCO_QUISQUI (KICHKI)', ('HUANUCO_HUANUCO_QUISQUI', 95)),
 ('PUNO_LAMPA_PUCARA', ('PUNO_LAMPA_PUCARA\xa0', 100)),
 ('TACNA_TARATA_ESTIQUE-PAMPA', ('TACNA_TARATA_ESTIQUE PAMPA', 100)),
 ('LAMBAYEQUE_FERREсFE_PUEBLO NUEVO',
  ('LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO', 97)),
 ('ICA_ICA_PACHACUTEC', ('ICA_ICA_PACHACÚTEC', 97)),
 ('LIMA METROPOLITANA_LIMA_CARABAYLLO', ('LIMA_LIMA_CARABAYLLO', 76)),
 ('LA LIBERTAD_GRAN CHIMU_SAYAPULLO',
  ('LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO', 98)),
 ('LIMA METROPOLITANA_LIMA_COMAS', ('LIMA_LIMA_COMAS', 72)),
 ('LA LIBERTAD_VIRU_VIRU', ('LA LIBERTAD_VIRÚ_VIRÚ', 95)),
 ('LIMA METROPOLITANA_LIMA_SAN JUAN DE LURIGANCHO',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LIMA_CAхTE_CHILCA', ('LIMA_CAÑETE_CHILCA', 94)),
 ('AYACUCHO_HUAMANGA_JESUS NAZARENO',
  ('AYACUCHO_HUAMANGA_JESÚS NAZARENO', 98)),
 ('LIMA METROPOLITANA_LIMA_SAN BARTOLO', ('LIMA_LIMA_SAN BARTOLO', 86)),
 ('AYACUCHO_VILCAS HUAMAN_ACCOMARCA',
  ('AYACUCHO_VILCAS-HUAMAN_ACCOMARCA', 100)),
 ('LIMA_CAхTE_ZUÑIGA', ('LIMA_CAÑETE_ZÚÑIGA', 90)),
 ('LIMA METROPOLITANA_LIMA_LOS OLIVOS', ('LIMA_LIMA_LOS OLIVOS', 86)),
 ('AYACUCHO_VILCAS HUAMAN_INDEPENDENCIA',
  ('AYACUCHO_VILCAS-HUAMAN_INDEPENDENCIA', 100)),
 ('APURIMAC_CHINCHEROS_ANCO_HUALLO', ('APURIMAC_CHINCHEROS_ANCO HUALLO', 97)),
 ('LAMBAYEQUE_CHICLAYO_MONSEFU', ('LAMBAYEQUE_CHICLAYO_MONSEFÚ', 98)),
 ('AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS',
  ('AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS', 99)),
 ('LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO',
  ('LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO', 98)),
 ('CUSCO_ACOMAYO_SANGARARA', ('CUSCO_ACOMAYO_SANGARARA\xa0', 100)),
 ('UCAYALI_PADRE ABAD_nan', ('UCAYALI_PADRE ABAD_ALEXANDER VON HUMBOLDT', 86)),
 ('LIMA METROPOLITANA_LIMA_SANTA MARIA DEL MAR',
  ('LIMA_LIMA_JESUS MARIA', 86)),
 ('LORETO_DATEM DEL MARAяN_MORONA', ('LORETO_DATEM DEL MARAÑON_MORONA', 97)),
 ('HUANUCO_MARAяN_LA MORADA', ('HUANUCO_MARAÑON_LA MORADA', 96)),
 ('ICA_NASCA_EL INGENIO', ('ICA_NAZCA_EL INGENIO', 95)),
 ('AREQUIPA_CAMANA_CAMANA', ('AREQUIPA_CAMANA_CAMANA\xa0', 100)),
 ('LIMA METROPOLITANA_LIMA_ATE', ('LIMA_LIMA_ATE', 69)),
 ('UCAYALI_PURUS_nan', ('UCAYALI_PURÚS_PURÚS', 76)),
 ('LIMA METROPOLITANA_LIMA_LA MOLINA', ('LIMA_LIMA_LA MOLINA', 86)),
 ('JUNIN_HUANCAYO_PUCARA', ('JUNIN_HUANCAYO_PUCARA\xa0', 100)),
 ('LIMA_CAхTE_NUEVO IMPERIAL', ('LIMA_CAÑETE_NUEVO IMPERIAL', 96)),
 ('CAJAMARCA_CAJAMARCA_JESUS', ('CAJAMARCA_CAJAMARCA_JESÚS', 98)),
 ('LAMBAYEQUE_LAMBAYEQUE_TUCUME', ('LAMBAYEQUE_LAMBAYEQUE_TÚCUME', 98)),
 ('ICA_NASCA_NASCA', ('ICA_NAZCA_NAZCA', 87)),
 ('LIMA METROPOLITANA_LIMA_SAN BORJA', ('LIMA_LIMA_SAN BORJA', 86)),
 ('LORETO_DATEM DEL MARAяN_CAHUAPANAS',
  ('LORETO_DATEM DEL MARAÑON_CAHUAPANAS', 97)),
 ('LORETO_DATEM DEL MARAяN_MANSERICHE',
  ('LORETO_DATEM DEL MARAÑON_MANSERICHE', 97)),
 ('LIMA METROPOLITANA_LIMA_SAN MIGUEL', ('LIMA_LIMA_SAN MIGUEL', 86)),
 ('LAMBAYEQUE_FERREсFE_CAÑARIS', ('LAMBAYEQUE_FERREÑAFE_CAÑARIS', 96)),
 ('HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE',
  ('HUANCAVELICA_ANGARAES_HUALLAY GRANDE', 99)),
 ('LIMA_CAхTE_QUILMANA', ('LIMA_CAÑETE_QUILMANA\xa0', 95)),
 ('LIMA METROPOLITANA_LIMA_PUNTA NEGRA', ('LIMA_LIMA_PUNTA NEGRA', 86)),
 ('LA LIBERTAD_GRAN CHIMU_CASCAS', ('LA LIBERTAD_GRAN CHIMÚ_CASCAS', 98)),
 ('JUNIN_SATIPO_VIZCATÁN DEL ENE', ('JUNIN_SATIPO_VIZCATAN DEL ENE', 98)),
 ('HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA',
  ('HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA', 98)),
 ('LIMA_CAхTE_COAYLLO', ('LIMA_CAÑETE_COAYLLO', 94)),
 ('HUANUCO_MARAяN_CHOLON', ('HUANUCO_MARAÑON_CHOLON', 95)),
 ('LIMA METROPOLITANA_LIMA_LIMA', ('LIMA_LIMA_LIMA', 71)),
 ('LIMA METROPOLITANA_LIMA_PUCUSANA', ('LIMA_LIMA_PUCUSANA', 75)),
 ('LIMA_CAхTE_MALA', ('LIMA_CAÑETE_MALA', 93)),
 ('LIMA METROPOLITANA_LIMA_SANTIAGO DE SURCO',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN ISIDRO', ('LIMA_LIMA_SAN ISIDRO', 86)),
 ('ICA_PISCO_TUPAC AMARU INCA', ('ICA_PISCO_TÚPAC AMARU INCA', 98)),
 ('LIMA METROPOLITANA_LIMA_SURQUILLO', ('LIMA_LIMA_SURQUILLO', 76)),
 ('LIMA METROPOLITANA_LIMA_CHACLACAYO', ('LIMA_LIMA_CHACLACAYO', 76)),
 ('LIMA METROPOLITANA_LIMA_LURIGANCHO', ('LIMA_LIMA_LURIGANCHO', 76)),
 ('HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAUN',
  ('HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAÚN', 99)),
 ('LIMA_CAхTE_SAN ANTONIO', ('LIMA_CAÑETE_SAN ANTONIO', 95)),
 ('LA LIBERTAD_VIRU_CHAO', ('LA LIBERTAD_VIRÚ_CHAO', 98)),
 ('CUSCO_CANAS_TUPAC AMARU', ('CUSCO_CANAS_TÚPAC AMARU', 98)),
 ('AYACUCHO_VILCAS HUAMAN_CARHUANCA',
  ('AYACUCHO_VILCAS-HUAMAN_CARHUANCA', 100)),
 ('LIMA_CAхTE_PACARAN', ('LIMA_CAÑETE_PACARAN', 94)),
 ('LIMA METROPOLITANA_LIMA_MIRAFLORES', ('LIMA_LIMA_MIRAFLORES', 76)),
 ('PIURA_SECHURA_RINCONADA LLICUAR', ('PIURA_SECHURA_RINCONADA-LLICUAR', 100)),
 ('LAMBAYEQUE_CHICLAYO_OYOTUN', ('LAMBAYEQUE_CHICLAYO_OYOTÚN', 98)),
 ('CAJAMARCA_JAEN_PUCARA', ('CAJAMARCA_JAEN_PUCARA\xa0', 100)),
 ('LIMA_CAхTE_CERRO AZUL', ('LIMA_CAÑETE_CERRO AZUL', 95)),
 ('HUANCAVELICA_ANGARAES_HUANCA-HUANCA',
  ('HUANCAVELICA_ANGARAES_HUANCA HUANCA', 100)),
 ('ICA_ICA_SAN JOSE DE LOS MOLINOS', ('ICA_ICA_SAN JOSE DE  LOS MOLINOS', 98)),
 ('HUANUCO_LAURICOCHA_JESUS', ('HUANUCO_LAURICOCHA_JESÚS', 98)),
 ('LIMA METROPOLITANA_LIMA_RIMAC', ('LIMA_LIMA_RIMAC', 72)),
 ('JUNIN_YAULI_SANTA BARBARA DE CARHUACAYAN',
  ('JUNIN_YAULI_SANTA BARBARA DE CARHUACAYáN', 99)),
 ('JUNIN_CHUPACA_SAN JUAN DE ISCOS', ('JUNIN_CHUPACA_SAN JUAN DE YSCOS', 97)),
 ('LAMBAYEQUE_FERREсFE_FERREÑAFE', ('LAMBAYEQUE_FERREÑAFE_FERREÑAFE', 96)),
 ('LIMA_CAхTE_SANTA CRUZ DE FLORES', ('LIMA_CAÑETE_SANTA CRUZ DE FLORES', 97)),
 ('LIMA METROPOLITANA_LIMA_LURIN', ('LIMA_LIMA_LURIN', 72)),
 ('LIMA METROPOLITANA_LIMA_INDEPENDENCIA', ('LIMA_LIMA_INDEPENDENCIA', 78)),
 ('AYACUCHO_VILCAS HUAMAN_SAURAMA', ('AYACUCHO_VILCAS-HUAMAN_SAURAMA', 100)),
 ('LIMA METROPOLITANA_LIMA_SAN LUIS', ('LIMA_CAÑETE_SAN LUIS', 86)),
 ('LAMBAYEQUE_FERREсFE_INCAHUASI', ('LAMBAYEQUE_FERREÑAFE_INCAHUASI', 97)),
 ('LIMA_CAхTE_IMPERIAL', ('LIMA_CAÑETE_IMPERIAL', 95)),
 ('AYACUCHO_VILCAS HUAMAN_VILCAS HUAMAN',
  ('AYACUCHO_VILCAS-HUAMAN_VILCAS HUAMAN', 100)),
 ('LIMA METROPOLITANA_LIMA_SAN JUAN DE MIRAFLORES',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LORETO_DATEM DEL MARAяN_ANDOAS', ('LORETO_DATEM DEL MARAÑON_ANDOAS', 97)),
 ('ICA_NASCA_MARCONA', ('ICA_NAZCA_MARCONA', 94)),
 ('ANCASH_SANTA_CACERES DEL PERU', ('ANCASH_SANTA_CACERES DEL PERÚ', 98)),
 ('LIMA METROPOLITANA_LIMA_LA VICTORIA', ('LIMA_LIMA_LA VICTORIA', 86)),
 ('SAN MARTIN_RIOJA_ELIAS SOPLIN VARGAS',
  ('SAN MARTIN_RIOJA_ELIAS SOPLíN VARGAS', 99)),
 ('LIMA_YAUYOS_ALLAUCA', ('LIMA_YAUYOS_AYAUCA', 92)),
 ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO',
  ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED', 99)),
 ('HUANUCO_MARAяN_SAN BUENAVENTURA', ('HUANUCO_MARAÑON_SAN BUENAVENTURA', 97)),
 ('AYACUCHO_VILCAS HUAMAN_HUAMBALPA',
  ('AYACUCHO_VILCAS-HUAMAN_HUAMBALPA', 100)),
 ('LIMA_CAхTE_LUNAHUANA', ('LIMA_CAÑETE_LUNAHUANA\xa0', 95)),
 ('LAMBAYEQUE_FERREсFE_PITIPO', ('LAMBAYEQUE_FERREÑAFE_PITIPO', 96)),
 ('LIMA METROPOLITANA_LIMA_PUNTA HERMOSA', ('LIMA_LIMA_PUNTA HERMOSA', 86)),
 ('LIMA METROPOLITANA_LIMA_LINCE', ('LIMA_LIMA_LINCE', 72)),
 ('LIMA METROPOLITANA_LIMA_PACHACAMAC', ('LIMA_LIMA_PACHACAMAC', 76)),
 ('JUNIN_JAUJA_TUNAN MARCA', ('JUNIN_JAUJA_TUNAN-MARCA', 100)),
 ('LIMA METROPOLITANA_LIMA_BREÑA', ('LIMA_LIMA_BREÑA', 71)),
 ('LIMA METROPOLITANA_LIMA_VILLA MARIA DEL TRIUNFO',
  ('LORETO_DATEM DEL MARAÑON_ANDOAS', 86)),
 ('LIMA METROPOLITANA_LIMA_EL AGUSTINO', ('LIMA_LIMA_EL AGUSTINO', 86)),
 ('LIMA METROPOLITANA_LIMA_ANCON', ('LIMA_LIMA_ANCON', 72)),
 ('LA LIBERTAD_GRAN CHIMU_LUCMA', ('LA LIBERTAD_GRAN CHIMÚ_LUCMA', 98)),
 ('SAN MARTIN_SAN MARTIN_PAPAPLAYA', ('SAN MARTIN_SAN MARTIN_PAPA-PLAYA', 98)),
 ('LA LIBERTAD_GRAN CHIMU_MARMOT', ('LA LIBERTAD_GRAN CHIMÚ_MARMOT', 98)),
 ('LIMA_CAхTE_CALANGO', ('LIMA_CAÑETE_CALANGO', 94)),
 ('ICA_NASCA_CHANGUILLO', ('ICA_NAZCA_CHANGUILLO', 95)),
 ('LIMA METROPOLITANA_LIMA_SAN MARTIN DE PORRES',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('AREQUIPA_CAMANA_MARIANO NICOLAS VALCARCEL',
  ('AREQUIPA_CAMANA_MARIANO NICOLAS VALCáRCEL', 99)),
 ('LIMA METROPOLITANA_LIMA_MAGDALENA DEL MAR',
  ('LIMA_LIMA_MAGDALENA DEL MAR', 86)),
 ('JUNIN_JAUJA_MASMA CHICCHE', ('JUNIN_JAUJA_MASMA-CHICCHE', 100)),
 ('HUANUCO_MARAяN_HUACRACHUCO', ('HUANUCO_MARAÑON_HUACRACHUCO', 96)),
 ('LIMA METROPOLITANA_LIMA_BARRANCO', ('LIMA_LIMA_BARRANCO', 75)),
 ('HUANCAVELICA_CASTROVIRREYNA_TANTARA',
  ('HUANCAVELICA_CASTROVIRREYNA_TANTARA\xa0', 100)),
 ('AYACUCHO_VILCAS HUAMAN_CONCEPCION',
  ('AYACUCHO_VILCAS-HUAMAN_CONCEPCION', 100)),
 ('LIMA METROPOLITANA_LIMA_VILLA EL SALVADOR',
  ('LIMA_LIMA_VILLA EL SALVADOR', 86)),
 ('LIMA_CAхTE_SAN LUIS', ('LIMA_CAÑETE_SAN LUIS', 95)),
 ('LA LIBERTAD_VIRU_GUADALUPITO', ('LA LIBERTAD_VIRÚ_GUADALUPITO', 98)),
 ('PASCO_OXAPAMPA_PUERTO BERMUDEZ', ('PASCO_OXAPAMPA_PUERTO BERMÚDEZ', 98)),
 ('LORETO_DATEM DEL MARAяN_PASTAZA', ('LORETO_DATEM DEL MARAÑON_PASTAZA', 97)),
 ('LIMA METROPOLITANA_LIMA_CIENEGUILLA', ('LIMA_LIMA_CIENEGUILLA', 77))]

In [86]:
changesDis={getBest(c,onlyDis)[0]:c for c in onlyCrim if getBest(c,onlyDis)[1]==100}
changesDis

{'SAN MARTIN_PICOTA_TRES-UNIDOS': 'SAN MARTIN_PICOTA_TRES UNIDOS',
 'AYACUCHO_VILCAS-HUAMAN_VISCHONGO': 'AYACUCHO_VILCAS HUAMAN_VISCHONGO',
 'PUNO_LAMPA_PUCARA\xa0': 'PUNO_LAMPA_PUCARA',
 'TACNA_TARATA_ESTIQUE PAMPA': 'TACNA_TARATA_ESTIQUE-PAMPA',
 'AYACUCHO_VILCAS-HUAMAN_ACCOMARCA': 'AYACUCHO_VILCAS HUAMAN_ACCOMARCA',
 'AYACUCHO_VILCAS-HUAMAN_INDEPENDENCIA': 'AYACUCHO_VILCAS HUAMAN_INDEPENDENCIA',
 'CUSCO_ACOMAYO_SANGARARA\xa0': 'CUSCO_ACOMAYO_SANGARARA',
 'AREQUIPA_CAMANA_CAMANA\xa0': 'AREQUIPA_CAMANA_CAMANA',
 'JUNIN_HUANCAYO_PUCARA\xa0': 'JUNIN_HUANCAYO_PUCARA',
 'AYACUCHO_VILCAS-HUAMAN_CARHUANCA': 'AYACUCHO_VILCAS HUAMAN_CARHUANCA',
 'PIURA_SECHURA_RINCONADA-LLICUAR': 'PIURA_SECHURA_RINCONADA LLICUAR',
 'CAJAMARCA_JAEN_PUCARA\xa0': 'CAJAMARCA_JAEN_PUCARA',
 'HUANCAVELICA_ANGARAES_HUANCA HUANCA': 'HUANCAVELICA_ANGARAES_HUANCA-HUANCA',
 'AYACUCHO_VILCAS-HUAMAN_SAURAMA': 'AYACUCHO_VILCAS HUAMAN_SAURAMA',
 'AYACUCHO_VILCAS-HUAMAN_VILCAS HUAMAN': 'AYACUCHO_VILCAS HUAMAN_VILCAS HUAMAN',
 'AYACUCHO_VILCAS-HUAMAN_HUAMBALPA': 'AYACUCHO_VILCAS HUAMAN_HUAMBALPA',
 'JUNIN_JAUJA_TUNAN-MARCA': 'JUNIN_JAUJA_TUNAN MARCA',
 'JUNIN_JAUJA_MASMA-CHICCHE': 'JUNIN_JAUJA_MASMA CHICCHE',
 'HUANCAVELICA_CASTROVIRREYNA_TANTARA\xa0': 'HUANCAVELICA_CASTROVIRREYNA_TANTARA',
 'AYACUCHO_VILCAS-HUAMAN_CONCEPCION': 'AYACUCHO_VILCAS HUAMAN_CONCEPCION'}

In [87]:
dis.replace({'merger':changesDis},inplace=True)

In [88]:
onlyCrim=set(crim.merger) - set(dis.merger)
onlyDis=set(dis.merger)-set(crim.merger)
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[('APURIMAC_AYMARAES_CARAYBAMBA', ('APURIMAC_AYMARAES_CARAIBAMBA', 96)),
 ('LIMA METROPOLITANA_LIMA_JESUS MARIA', ('LIMA_LIMA_JESUS MARIA', 86)),
 ('UCAYALI_ATALAYA_YURUA', ('UCAYALI_ATALAYA_YURÚA', 98)),
 ('LIMA METROPOLITANA_LIMA_CHORRILLOS', ('LIMA_LIMA_CHORRILLOS', 76)),
 ('LIMA METROPOLITANA_LIMA_PUEBLO LIBRE', ('LIMA_LIMA_LINCE', 57)),
 ('LIMA METROPOLITANA_LIMA_SANTA ANITA', ('LIMA_LIMA_SANTA ANITA', 86)),
 ('LIMA_CAхTE_SAN VICENTE DE CAÑETE',
  ('LIMA_CAÑETE_SAN VICENTE DE CAÑETE', 97)),
 ('LIMA_CAхTE_ASIA', ('LIMA_CAÑETE_ASIA', 93)),
 ('LIMA METROPOLITANA_LIMA_PUENTE PIEDRA', ('LIMA_LIMA_PUENTE PIEDRA', 86)),
 ('ICA_NASCA_VISTA ALEGRE', ('ICA_NAZCA_VISTA ALEGRE', 95)),
 ('LIMA METROPOLITANA_LIMA_SANTA ROSA', ('LIMA_LIMA_SANTA ROSA', 86)),
 ('LORETO_DATEM DEL MARAяN_BARRANCA',
  ('LORETO_DATEM DEL MARAÑON_BARRANCA', 97)),
 ('HUANUCO_HUANUCO_QUISQUI (KICHKI)', ('HUANUCO_HUANUCO_QUISQUI', 95)),
 ('LAMBAYEQUE_FERREсFE_PUEBLO NUEVO',
  ('LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO', 97)),
 ('ICA_ICA_PACHACUTEC', ('ICA_ICA_PACHACÚTEC', 97)),
 ('LIMA METROPOLITANA_LIMA_CARABAYLLO', ('LIMA_LIMA_CARABAYLLO', 76)),
 ('LA LIBERTAD_GRAN CHIMU_SAYAPULLO',
  ('LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO', 98)),
 ('LIMA METROPOLITANA_LIMA_COMAS', ('LIMA_LIMA_COMAS', 72)),
 ('LA LIBERTAD_VIRU_VIRU', ('LA LIBERTAD_VIRÚ_VIRÚ', 95)),
 ('LIMA METROPOLITANA_LIMA_SAN JUAN DE LURIGANCHO',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LIMA_CAхTE_CHILCA', ('LIMA_CAÑETE_CHILCA', 94)),
 ('AYACUCHO_HUAMANGA_JESUS NAZARENO',
  ('AYACUCHO_HUAMANGA_JESÚS NAZARENO', 98)),
 ('LIMA METROPOLITANA_LIMA_SAN BARTOLO', ('LIMA_LIMA_SAN BARTOLO', 86)),
 ('LIMA METROPOLITANA_LIMA_LOS OLIVOS', ('LIMA_LIMA_LOS OLIVOS', 86)),
 ('LIMA_CAхTE_ZUÑIGA', ('LIMA_CAÑETE_ZÚÑIGA', 90)),
 ('APURIMAC_CHINCHEROS_ANCO_HUALLO', ('APURIMAC_CHINCHEROS_ANCO HUALLO', 97)),
 ('LAMBAYEQUE_CHICLAYO_MONSEFU', ('LAMBAYEQUE_CHICLAYO_MONSEFÚ', 98)),
 ('AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS',
  ('AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS', 99)),
 ('LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO',
  ('LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO', 98)),
 ('UCAYALI_PADRE ABAD_nan', ('UCAYALI_PADRE ABAD_ALEXANDER VON HUMBOLDT', 86)),
 ('LIMA METROPOLITANA_LIMA_SANTA MARIA DEL MAR',
  ('LIMA_LIMA_JESUS MARIA', 86)),
 ('LORETO_DATEM DEL MARAяN_MORONA', ('LORETO_DATEM DEL MARAÑON_MORONA', 97)),
 ('HUANUCO_MARAяN_LA MORADA', ('HUANUCO_MARAÑON_LA MORADA', 96)),
 ('ICA_NASCA_EL INGENIO', ('ICA_NAZCA_EL INGENIO', 95)),
 ('LIMA METROPOLITANA_LIMA_ATE', ('LIMA_LIMA_ATE', 69)),
 ('UCAYALI_PURUS_nan', ('UCAYALI_PURÚS_PURÚS', 76)),
 ('LIMA METROPOLITANA_LIMA_LA MOLINA', ('LIMA_LIMA_LA MOLINA', 86)),
 ('LIMA_CAхTE_NUEVO IMPERIAL', ('LIMA_CAÑETE_NUEVO IMPERIAL', 96)),
 ('CAJAMARCA_CAJAMARCA_JESUS', ('CAJAMARCA_CAJAMARCA_JESÚS', 98)),
 ('LAMBAYEQUE_LAMBAYEQUE_TUCUME', ('LAMBAYEQUE_LAMBAYEQUE_TÚCUME', 98)),
 ('ICA_NASCA_NASCA', ('ICA_NAZCA_NAZCA', 87)),
 ('LIMA METROPOLITANA_LIMA_SAN BORJA', ('LIMA_LIMA_SAN BORJA', 86)),
 ('LORETO_DATEM DEL MARAяN_CAHUAPANAS',
  ('LORETO_DATEM DEL MARAÑON_CAHUAPANAS', 97)),
 ('LORETO_DATEM DEL MARAяN_MANSERICHE',
  ('LORETO_DATEM DEL MARAÑON_MANSERICHE', 97)),
 ('LIMA METROPOLITANA_LIMA_SAN MIGUEL', ('LIMA_LIMA_SAN MIGUEL', 86)),
 ('LAMBAYEQUE_FERREсFE_CAÑARIS', ('LAMBAYEQUE_FERREÑAFE_CAÑARIS', 96)),
 ('HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE',
  ('HUANCAVELICA_ANGARAES_HUALLAY GRANDE', 99)),
 ('LIMA_CAхTE_QUILMANA', ('LIMA_CAÑETE_QUILMANA\xa0', 95)),
 ('LIMA METROPOLITANA_LIMA_PUNTA NEGRA', ('LIMA_LIMA_PUNTA NEGRA', 86)),
 ('LA LIBERTAD_GRAN CHIMU_CASCAS', ('LA LIBERTAD_GRAN CHIMÚ_CASCAS', 98)),
 ('JUNIN_SATIPO_VIZCATÁN DEL ENE', ('JUNIN_SATIPO_VIZCATAN DEL ENE', 98)),
 ('HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA',
  ('HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA', 98)),
 ('LIMA_CAхTE_COAYLLO', ('LIMA_CAÑETE_COAYLLO', 94)),
 ('HUANUCO_MARAяN_CHOLON', ('HUANUCO_MARAÑON_CHOLON', 95)),
 ('LIMA METROPOLITANA_LIMA_LIMA', ('LIMA_LIMA_LIMA', 71)),
 ('LIMA METROPOLITANA_LIMA_PUCUSANA', ('LIMA_LIMA_PUCUSANA', 75)),
 ('LIMA_CAхTE_MALA', ('LIMA_CAÑETE_MALA', 93)),
 ('LIMA METROPOLITANA_LIMA_SANTIAGO DE SURCO',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN ISIDRO', ('LIMA_LIMA_SAN ISIDRO', 86)),
 ('ICA_PISCO_TUPAC AMARU INCA', ('ICA_PISCO_TÚPAC AMARU INCA', 98)),
 ('LIMA METROPOLITANA_LIMA_SURQUILLO', ('LIMA_LIMA_SURQUILLO', 76)),
 ('LIMA METROPOLITANA_LIMA_CHACLACAYO', ('LIMA_LIMA_CHACLACAYO', 76)),
 ('LIMA METROPOLITANA_LIMA_LURIGANCHO', ('LIMA_LIMA_LURIGANCHO', 76)),
 ('HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAUN',
  ('HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAÚN', 99)),
 ('LIMA_CAхTE_SAN ANTONIO', ('LIMA_CAÑETE_SAN ANTONIO', 95)),
 ('LA LIBERTAD_VIRU_CHAO', ('LA LIBERTAD_VIRÚ_CHAO', 98)),
 ('CUSCO_CANAS_TUPAC AMARU', ('CUSCO_CANAS_TÚPAC AMARU', 98)),
 ('LIMA_CAхTE_PACARAN', ('LIMA_CAÑETE_PACARAN', 94)),
 ('LIMA METROPOLITANA_LIMA_MIRAFLORES', ('LIMA_LIMA_MIRAFLORES', 76)),
 ('LAMBAYEQUE_CHICLAYO_OYOTUN', ('LAMBAYEQUE_CHICLAYO_OYOTÚN', 98)),
 ('LIMA_CAхTE_CERRO AZUL', ('LIMA_CAÑETE_CERRO AZUL', 95)),
 ('ICA_ICA_SAN JOSE DE LOS MOLINOS', ('ICA_ICA_SAN JOSE DE  LOS MOLINOS', 98)),
 ('HUANUCO_LAURICOCHA_JESUS', ('HUANUCO_LAURICOCHA_JESÚS', 98)),
 ('LIMA METROPOLITANA_LIMA_RIMAC', ('LIMA_LIMA_RIMAC', 72)),
 ('JUNIN_YAULI_SANTA BARBARA DE CARHUACAYAN',
  ('JUNIN_YAULI_SANTA BARBARA DE CARHUACAYáN', 99)),
 ('JUNIN_CHUPACA_SAN JUAN DE ISCOS', ('JUNIN_CHUPACA_SAN JUAN DE YSCOS', 97)),
 ('LAMBAYEQUE_FERREсFE_FERREÑAFE', ('LAMBAYEQUE_FERREÑAFE_FERREÑAFE', 96)),
 ('LIMA_CAхTE_SANTA CRUZ DE FLORES', ('LIMA_CAÑETE_SANTA CRUZ DE FLORES', 97)),
 ('LIMA METROPOLITANA_LIMA_LURIN', ('LIMA_LIMA_LURIN', 72)),
 ('LIMA METROPOLITANA_LIMA_INDEPENDENCIA', ('LIMA_LIMA_INDEPENDENCIA', 78)),
 ('LIMA METROPOLITANA_LIMA_SAN LUIS', ('LIMA_CAÑETE_SAN LUIS', 86)),
 ('LAMBAYEQUE_FERREсFE_INCAHUASI', ('LAMBAYEQUE_FERREÑAFE_INCAHUASI', 97)),
 ('LIMA_CAхTE_IMPERIAL', ('LIMA_CAÑETE_IMPERIAL', 95)),
 ('LIMA METROPOLITANA_LIMA_SAN JUAN DE MIRAFLORES',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LORETO_DATEM DEL MARAяN_ANDOAS', ('LORETO_DATEM DEL MARAÑON_ANDOAS', 97)),
 ('ICA_NASCA_MARCONA', ('ICA_NAZCA_MARCONA', 94)),
 ('ANCASH_SANTA_CACERES DEL PERU', ('ANCASH_SANTA_CACERES DEL PERÚ', 98)),
 ('LIMA METROPOLITANA_LIMA_LA VICTORIA', ('LIMA_LIMA_LA VICTORIA', 86)),
 ('SAN MARTIN_RIOJA_ELIAS SOPLIN VARGAS',
  ('SAN MARTIN_RIOJA_ELIAS SOPLíN VARGAS', 99)),
 ('LIMA_YAUYOS_ALLAUCA', ('LIMA_YAUYOS_AYAUCA', 92)),
 ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO',
  ('CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED', 99)),
 ('HUANUCO_MARAяN_SAN BUENAVENTURA', ('HUANUCO_MARAÑON_SAN BUENAVENTURA', 97)),
 ('LIMA_CAхTE_LUNAHUANA', ('LIMA_CAÑETE_LUNAHUANA\xa0', 95)),
 ('LAMBAYEQUE_FERREсFE_PITIPO', ('LAMBAYEQUE_FERREÑAFE_PITIPO', 96)),
 ('LIMA METROPOLITANA_LIMA_PUNTA HERMOSA', ('LIMA_LIMA_PUNTA HERMOSA', 86)),
 ('LIMA METROPOLITANA_LIMA_LINCE', ('LIMA_LIMA_LINCE', 72)),
 ('LIMA METROPOLITANA_LIMA_PACHACAMAC', ('LIMA_LIMA_PACHACAMAC', 76)),
 ('LIMA METROPOLITANA_LIMA_BREÑA', ('LIMA_LIMA_BREÑA', 71)),
 ('LIMA METROPOLITANA_LIMA_VILLA MARIA DEL TRIUNFO',
  ('LORETO_DATEM DEL MARAÑON_ANDOAS', 86)),
 ('LIMA METROPOLITANA_LIMA_EL AGUSTINO', ('LIMA_LIMA_EL AGUSTINO', 86)),
 ('LIMA METROPOLITANA_LIMA_ANCON', ('LIMA_LIMA_ANCON', 72)),
 ('LA LIBERTAD_GRAN CHIMU_LUCMA', ('LA LIBERTAD_GRAN CHIMÚ_LUCMA', 98)),
 ('SAN MARTIN_SAN MARTIN_PAPAPLAYA', ('SAN MARTIN_SAN MARTIN_PAPA-PLAYA', 98)),
 ('LA LIBERTAD_GRAN CHIMU_MARMOT', ('LA LIBERTAD_GRAN CHIMÚ_MARMOT', 98)),
 ('LIMA_CAхTE_CALANGO', ('LIMA_CAÑETE_CALANGO', 94)),
 ('ICA_NASCA_CHANGUILLO', ('ICA_NAZCA_CHANGUILLO', 95)),
 ('LIMA METROPOLITANA_LIMA_SAN MARTIN DE PORRES',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('AREQUIPA_CAMANA_MARIANO NICOLAS VALCARCEL',
  ('AREQUIPA_CAMANA_MARIANO NICOLAS VALCáRCEL', 99)),
 ('LIMA METROPOLITANA_LIMA_MAGDALENA DEL MAR',
  ('LIMA_LIMA_MAGDALENA DEL MAR', 86)),
 ('HUANUCO_MARAяN_HUACRACHUCO', ('HUANUCO_MARAÑON_HUACRACHUCO', 96)),
 ('LIMA METROPOLITANA_LIMA_BARRANCO', ('LIMA_LIMA_BARRANCO', 75)),
 ('LIMA METROPOLITANA_LIMA_VILLA EL SALVADOR',
  ('LIMA_LIMA_VILLA EL SALVADOR', 86)),
 ('LIMA_CAхTE_SAN LUIS', ('LIMA_CAÑETE_SAN LUIS', 95)),
 ('LA LIBERTAD_VIRU_GUADALUPITO', ('LA LIBERTAD_VIRÚ_GUADALUPITO', 98)),
 ('PASCO_OXAPAMPA_PUERTO BERMUDEZ', ('PASCO_OXAPAMPA_PUERTO BERMÚDEZ', 98)),
 ('LORETO_DATEM DEL MARAяN_PASTAZA', ('LORETO_DATEM DEL MARAÑON_PASTAZA', 97)),
 ('LIMA METROPOLITANA_LIMA_CIENEGUILLA', ('LIMA_LIMA_CIENEGUILLA', 77))]

In [90]:
changesCrim={c:getBest(c,onlyDis)[0] for c in onlyCrim if getBest(c,onlyDis)[1]>=90}
changesCrim

{'APURIMAC_AYMARAES_CARAYBAMBA': 'APURIMAC_AYMARAES_CARAIBAMBA',
 'UCAYALI_ATALAYA_YURUA': 'UCAYALI_ATALAYA_YURÚA',
 'LIMA_CAхTE_SAN VICENTE DE CAÑETE': 'LIMA_CAÑETE_SAN VICENTE DE CAÑETE',
 'LIMA_CAхTE_ASIA': 'LIMA_CAÑETE_ASIA',
 'ICA_NASCA_VISTA ALEGRE': 'ICA_NAZCA_VISTA ALEGRE',
 'LORETO_DATEM DEL MARAяN_BARRANCA': 'LORETO_DATEM DEL MARAÑON_BARRANCA',
 'HUANUCO_HUANUCO_QUISQUI (KICHKI)': 'HUANUCO_HUANUCO_QUISQUI',
 'LAMBAYEQUE_FERREсFE_PUEBLO NUEVO': 'LAMBAYEQUE_FERREÑAFE_PUEBLO NUEVO',
 'ICA_ICA_PACHACUTEC': 'ICA_ICA_PACHACÚTEC',
 'LA LIBERTAD_GRAN CHIMU_SAYAPULLO': 'LA LIBERTAD_GRAN CHIMÚ_SAYAPULLO',
 'LA LIBERTAD_VIRU_VIRU': 'LA LIBERTAD_VIRÚ_VIRÚ',
 'LIMA_CAхTE_CHILCA': 'LIMA_CAÑETE_CHILCA',
 'AYACUCHO_HUAMANGA_JESUS NAZARENO': 'AYACUCHO_HUAMANGA_JESÚS NAZARENO',
 'LIMA_CAхTE_ZUÑIGA': 'LIMA_CAÑETE_ZÚÑIGA',
 'APURIMAC_CHINCHEROS_ANCO_HUALLO': 'APURIMAC_CHINCHEROS_ANCO HUALLO',
 'LAMBAYEQUE_CHICLAYO_MONSEFU': 'LAMBAYEQUE_CHICLAYO_MONSEFÚ',
 'AYACUCHO_HUAMANGA_SAN JOSE DE TICLLAS': 'AYACUCHO_HUAMANGA_SAN JOSE  DE TICLLAS',
 'LAMBAYEQUE_FERREсFE_MANUEL ANTONIO MESONES MURO': 'LAMBAYEQUE_FERREÑAFE_MANUEL ANTONIO MESONES MURO',
 'LORETO_DATEM DEL MARAяN_MORONA': 'LORETO_DATEM DEL MARAÑON_MORONA',
 'HUANUCO_MARAяN_LA MORADA': 'HUANUCO_MARAÑON_LA MORADA',
 'ICA_NASCA_EL INGENIO': 'ICA_NAZCA_EL INGENIO',
 'LIMA_CAхTE_NUEVO IMPERIAL': 'LIMA_CAÑETE_NUEVO IMPERIAL',
 'CAJAMARCA_CAJAMARCA_JESUS': 'CAJAMARCA_CAJAMARCA_JESÚS',
 'LAMBAYEQUE_LAMBAYEQUE_TUCUME': 'LAMBAYEQUE_LAMBAYEQUE_TÚCUME',
 'LORETO_DATEM DEL MARAяN_CAHUAPANAS': 'LORETO_DATEM DEL MARAÑON_CAHUAPANAS',
 'LORETO_DATEM DEL MARAяN_MANSERICHE': 'LORETO_DATEM DEL MARAÑON_MANSERICHE',
 'LAMBAYEQUE_FERREсFE_CAÑARIS': 'LAMBAYEQUE_FERREÑAFE_CAÑARIS',
 'HUANCAVELICA_ANGARAES_HUAYLLAY GRANDE': 'HUANCAVELICA_ANGARAES_HUALLAY GRANDE',
 'LIMA_CAхTE_QUILMANA': 'LIMA_CAÑETE_QUILMANA\xa0',
 'LA LIBERTAD_GRAN CHIMU_CASCAS': 'LA LIBERTAD_GRAN CHIMÚ_CASCAS',
 'JUNIN_SATIPO_VIZCATÁN DEL ENE': 'JUNIN_SATIPO_VIZCATAN DEL ENE',
 'HUANUCO_MARAяN_SANTA ROSA DE ALTO YANAJANCA': 'HUANUCO_MARAÑON_SANTA ROSA DE ALTO YANAJANCA',
 'LIMA_CAхTE_COAYLLO': 'LIMA_CAÑETE_COAYLLO',
 'HUANUCO_MARAяN_CHOLON': 'HUANUCO_MARAÑON_CHOLON',
 'LIMA_CAхTE_MALA': 'LIMA_CAÑETE_MALA',
 'ICA_PISCO_TUPAC AMARU INCA': 'ICA_PISCO_TÚPAC AMARU INCA',
 'HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAUN': 'HUANUCO_LEONCIO PRADO_MARIANO DAMASO BERAÚN',
 'LIMA_CAхTE_SAN ANTONIO': 'LIMA_CAÑETE_SAN ANTONIO',
 'LA LIBERTAD_VIRU_CHAO': 'LA LIBERTAD_VIRÚ_CHAO',
 'CUSCO_CANAS_TUPAC AMARU': 'CUSCO_CANAS_TÚPAC AMARU',
 'LIMA_CAхTE_PACARAN': 'LIMA_CAÑETE_PACARAN',
 'LAMBAYEQUE_CHICLAYO_OYOTUN': 'LAMBAYEQUE_CHICLAYO_OYOTÚN',
 'LIMA_CAхTE_CERRO AZUL': 'LIMA_CAÑETE_CERRO AZUL',
 'ICA_ICA_SAN JOSE DE LOS MOLINOS': 'ICA_ICA_SAN JOSE DE  LOS MOLINOS',
 'HUANUCO_LAURICOCHA_JESUS': 'HUANUCO_LAURICOCHA_JESÚS',
 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYAN': 'JUNIN_YAULI_SANTA BARBARA DE CARHUACAYáN',
 'JUNIN_CHUPACA_SAN JUAN DE ISCOS': 'JUNIN_CHUPACA_SAN JUAN DE YSCOS',
 'LAMBAYEQUE_FERREсFE_FERREÑAFE': 'LAMBAYEQUE_FERREÑAFE_FERREÑAFE',
 'LIMA_CAхTE_SANTA CRUZ DE FLORES': 'LIMA_CAÑETE_SANTA CRUZ DE FLORES',
 'LAMBAYEQUE_FERREсFE_INCAHUASI': 'LAMBAYEQUE_FERREÑAFE_INCAHUASI',
 'LIMA_CAхTE_IMPERIAL': 'LIMA_CAÑETE_IMPERIAL',
 'LORETO_DATEM DEL MARAяN_ANDOAS': 'LORETO_DATEM DEL MARAÑON_ANDOAS',
 'ICA_NASCA_MARCONA': 'ICA_NAZCA_MARCONA',
 'ANCASH_SANTA_CACERES DEL PERU': 'ANCASH_SANTA_CACERES DEL PERÚ',
 'SAN MARTIN_RIOJA_ELIAS SOPLIN VARGAS': 'SAN MARTIN_RIOJA_ELIAS SOPLíN VARGAS',
 'LIMA_YAUYOS_ALLAUCA': 'LIMA_YAUYOS_AYAUCA',
 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLEDO': 'CAJAMARCA_CONTUMAZA_SANTA CRUZ DE TOLED',
 'HUANUCO_MARAяN_SAN BUENAVENTURA': 'HUANUCO_MARAÑON_SAN BUENAVENTURA',
 'LIMA_CAхTE_LUNAHUANA': 'LIMA_CAÑETE_LUNAHUANA\xa0',
 'LAMBAYEQUE_FERREсFE_PITIPO': 'LAMBAYEQUE_FERREÑAFE_PITIPO',
 'LA LIBERTAD_GRAN CHIMU_LUCMA': 'LA LIBERTAD_GRAN CHIMÚ_LUCMA',
 'SAN MARTIN_SAN MARTIN_PAPAPLAYA': 'SAN MARTIN_SAN MARTIN_PAPA-PLAYA',
 'LA LIBERTAD_GRAN CHIMU_MARMOT': 'LA LIBERTAD_GRAN CHIMÚ_MARMOT',
 'LIMA_CAхTE_CALANGO': 'LIMA_CAÑETE_CALANGO',
 'ICA_NASCA_CHANGUILLO': 'ICA_NAZCA_CHANGUILLO',
 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCARCEL': 'AREQUIPA_CAMANA_MARIANO NICOLAS VALCáRCEL',
 'HUANUCO_MARAяN_HUACRACHUCO': 'HUANUCO_MARAÑON_HUACRACHUCO',
 'LIMA_CAхTE_SAN LUIS': 'LIMA_CAÑETE_SAN LUIS',
 'LA LIBERTAD_VIRU_GUADALUPITO': 'LA LIBERTAD_VIRÚ_GUADALUPITO',
 'PASCO_OXAPAMPA_PUERTO BERMUDEZ': 'PASCO_OXAPAMPA_PUERTO BERMÚDEZ',
 'LORETO_DATEM DEL MARAяN_PASTAZA': 'LORETO_DATEM DEL MARAÑON_PASTAZA'}

In [91]:
crim.replace({'merger':changesCrim},inplace=True)
onlyCrim=set(crim.merger) - set(dis.merger)
onlyDis=set(dis.merger)-set(crim.merger)
[(c,getBest(c,onlyDis)) for c in onlyCrim]

[('LIMA METROPOLITANA_LIMA_SURQUILLO', ('LIMA_LIMA_SURQUILLO', 76)),
 ('LIMA METROPOLITANA_LIMA_JESUS MARIA', ('LIMA_LIMA_JESUS MARIA', 86)),
 ('LIMA METROPOLITANA_LIMA_CHACLACAYO', ('LIMA_LIMA_CHACLACAYO', 76)),
 ('LIMA METROPOLITANA_LIMA_LA VICTORIA', ('LIMA_LIMA_LA VICTORIA', 86)),
 ('LIMA METROPOLITANA_LIMA_CHORRILLOS', ('LIMA_LIMA_CHORRILLOS', 76)),
 ('LIMA METROPOLITANA_LIMA_ATE', ('LIMA_LIMA_ATE', 69)),
 ('UCAYALI_PURUS_nan', ('UCAYALI_PURÚS_PURÚS', 76)),
 ('LIMA METROPOLITANA_LIMA_LURIGANCHO', ('LIMA_LIMA_LURIGANCHO', 76)),
 ('LIMA METROPOLITANA_LIMA_PUEBLO LIBRE', ('LIMA_LIMA_LINCE', 57)),
 ('LIMA METROPOLITANA_LIMA_SANTA ANITA', ('LIMA_LIMA_SANTA ANITA', 86)),
 ('LIMA METROPOLITANA_LIMA_LA MOLINA', ('LIMA_LIMA_LA MOLINA', 86)),
 ('LIMA METROPOLITANA_LIMA_PUENTE PIEDRA', ('LIMA_LIMA_PUENTE PIEDRA', 86)),
 ('LIMA METROPOLITANA_LIMA_PUNTA HERMOSA', ('LIMA_LIMA_PUNTA HERMOSA', 86)),
 ('LIMA METROPOLITANA_LIMA_SANTA ROSA', ('LIMA_LIMA_SANTA ROSA', 86)),
 ('LIMA METROPOLITANA_LIMA_MIRAFLORES', ('LIMA_LIMA_MIRAFLORES', 76)),
 ('LIMA METROPOLITANA_LIMA_LINCE', ('LIMA_LIMA_LINCE', 72)),
 ('LIMA METROPOLITANA_LIMA_PACHACAMAC', ('LIMA_LIMA_PACHACAMAC', 76)),
 ('LIMA METROPOLITANA_LIMA_BREÑA', ('LIMA_LIMA_BREÑA', 71)),
 ('LIMA METROPOLITANA_LIMA_VILLA MARIA DEL TRIUNFO',
  ('LIMA_LIMA_SANTA MARIA DEL MAR', 86)),
 ('ICA_NASCA_NASCA', ('ICA_NAZCA_NAZCA', 87)),
 ('LIMA METROPOLITANA_LIMA_CIENEGUILLA', ('LIMA_LIMA_CIENEGUILLA', 77)),
 ('LIMA METROPOLITANA_LIMA_EL AGUSTINO', ('LIMA_LIMA_EL AGUSTINO', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN BORJA', ('LIMA_LIMA_SAN BORJA', 86)),
 ('LIMA METROPOLITANA_LIMA_RIMAC', ('LIMA_LIMA_RIMAC', 72)),
 ('LIMA METROPOLITANA_LIMA_ANCON', ('LIMA_LIMA_ANCON', 72)),
 ('LIMA METROPOLITANA_LIMA_SAN MIGUEL', ('LIMA_LIMA_SAN MIGUEL', 86)),
 ('LIMA METROPOLITANA_LIMA_LURIN', ('LIMA_LIMA_LURIN', 72)),
 ('LIMA METROPOLITANA_LIMA_INDEPENDENCIA', ('LIMA_LIMA_INDEPENDENCIA', 78)),
 ('LIMA METROPOLITANA_LIMA_PUNTA NEGRA', ('LIMA_LIMA_PUNTA NEGRA', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN LUIS', ('LIMA_LIMA_SAN LUIS', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN MARTIN DE PORRES',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LIMA METROPOLITANA_LIMA_CARABAYLLO', ('LIMA_LIMA_CARABAYLLO', 76)),
 ('LIMA METROPOLITANA_LIMA_COMAS', ('LIMA_LIMA_COMAS', 72)),
 ('LIMA METROPOLITANA_LIMA_SAN BARTOLO', ('LIMA_LIMA_SAN BARTOLO', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN JUAN DE LURIGANCHO',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('LIMA METROPOLITANA_LIMA_MAGDALENA DEL MAR',
  ('LIMA_LIMA_MAGDALENA DEL MAR', 86)),
 ('LIMA METROPOLITANA_LIMA_LOS OLIVOS', ('LIMA_LIMA_LOS OLIVOS', 86)),
 ('LIMA METROPOLITANA_LIMA_LIMA', ('LIMA_LIMA_LIMA', 71)),
 ('LIMA METROPOLITANA_LIMA_PUCUSANA', ('LIMA_LIMA_PUCUSANA', 75)),
 ('LIMA METROPOLITANA_LIMA_BARRANCO', ('LIMA_LIMA_BARRANCO', 75)),
 ('LIMA METROPOLITANA_LIMA_VILLA EL SALVADOR',
  ('LIMA_LIMA_VILLA EL SALVADOR', 86)),
 ('LIMA METROPOLITANA_LIMA_SANTIAGO DE SURCO',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86)),
 ('UCAYALI_PADRE ABAD_nan', ('UCAYALI_PADRE ABAD_ALEXANDER VON HUMBOLDT', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN ISIDRO', ('LIMA_LIMA_SAN ISIDRO', 86)),
 ('LIMA METROPOLITANA_LIMA_SANTA MARIA DEL MAR',
  ('LIMA_LIMA_JESUS MARIA', 86)),
 ('LIMA METROPOLITANA_LIMA_SAN JUAN DE MIRAFLORES',
  ('LIMA_LIMA_SANTIAGO DE SURCO', 86))]